# Dados curados dos 8 cirurgiões agendados pra diagnóstico CPP em 06/05/2026
# Fonte: cruzamento subagents + base CPP-Desafio-Maio2026/dossie/consolidado.json

CIRURGIOES = [
    {
        "slug": "tatiana-patruni",
        "ordem": 1,
        "hora": "11:00",
        "zoom": "https://us06web.zoom.us/j/87051724132",
        # IDENTIDADE (público + cirúrgico)
        "nome": "Dra. Tatiana Mauad Patruni",
        "nome_lista": "Dra Tatiana Patrubi",
        "correcao_grafia": "Patrick listou como 'Patrubi'. Grafia oficial em CRM-PR, site, hospitais e Doctoralia: PATRUNI (com N).",
        "especialidade": "Otorrinolaringologia",
        "subespecialidade": "Rinoplastia · Cirurgia Plástica da Face · Otologia",
        "cidade": "Curitiba",
        "estado": "PR",
        "crm": "CRM-PR 25960 · RQE Otorrino 1855",
        "formacao": [
            "UFPR — Universidade Federal do Paraná (2008)",
            "Residência Otorrinolaringologia — PUC-PR / Santa Casa + Cajuru (2009-2011)",
            "Especialização em Otologia e Cirurgia de Implante Coclear (2012)",
            "Pós-graduação em Perícias Médicas — IPOG (2014)",
        ],
        "estruturas": [
            "Hospital São Vicente · Hospital Marcelino Champagnat · Novaclínica (SJP)",
            "Consultório próprio — R. Prof. João Argemiro Loyola, 152 · Seminário · Curitiba",
            "Médica auditora da Prefeitura de Curitiba",
            "Preceptora da Residência de Otorrino — HU Evangélico Curitiba",
            "Docente em pós-graduação de medicina estética",
        ],
        "credenciais": [
            "Preceptora de residência médica (HU Evangélico Curitiba)",
            "Trabalhos em congresso: Síndrome de Binder (2010) e Síndrome de Gradenigo (2012)",
            "14 anos de experiência clínica em otorrino + rinoplastia",
            "Tri-língue: Português, Inglês, Espanhol",
        ],
        "instagram": "@dratatianapatruni",
        "instagram_url": "https://www.instagram.com/dratatianapatruni/",
        "instagram_aberto": True,
        "instagram_seguidores": "9.891",
        "instagram_posts": "828",
        "instagram_bio": '"Dra Tatiana Patruni - Rinoplastia"',
        "instagram_tom": "Educativo / didático (pré-pós rinoplastia, calo ósseo, casos), mas sem narrativa pessoal",
        "site": "https://dratatianapatruni.com.br/",
        "doctoralia": "https://www.doctoralia.com.br/tatiana-mauad-patruni/otorrino/curitiba",
        "linkedin": None,
        "tagline_atual": '"Beleza natural sem mudar drasticamente"',

        # POSICIONAMENTO PÚBLICO (apresentável)
        "posicionamento_atual_publico": "Otorrino que faz rinoplastia natural com viés funcional+estético. Filosofia 'beleza natural sem mudar drasticamente'.",
        "potencial_publico": "Tatiana, sua trajetória conta uma história de profundidade técnica — UFPR, PUC, Otologia, Implante Coclear, Rinoplastia, preceptoria, docência. O próximo capítulo não é sobre acumular mais especialidades. É sobre <strong>concentrar o que você já é</strong> em uma marca que o paciente premium reconheça em 3 segundos.",

        # CIRÚRGICO (oculto)
        "perfil_cpp": "GAVIÃO com traços de PATO",
        "score_compra": None,  # não estava na base do desafio (entrou direto pelo R$1k)
        "perfil_evidencias": [
            "Investiu em marca pessoal (site, IG dedicado @dratatianapatruni com handle 'rinoplastia')",
            "Pagou R$1.000 de sinal — sinal de ambição ativa",
            "MAS 14 anos de carreira e ainda 9k seguidores · 0 reviews Doctoralia",
            "Aceita Unimed/Bradesco/Sanepar — não rompeu para particular puro",
            "Estrutura espalhada: consultório + 3 hospitais + auditoria municipal + preceptoria + docência",
        ],
        "dores_top3": [
            ("Estagnação financeira + ticket comprimido", "Aceita 3 convênios grandes — sinal de volume com ticket pressionado, apesar do CV de elite."),
            ("Cansaço de produzir conteúdo sem retorno proporcional", "828 posts e 9,9k seguidores em nicho que viraliza com antes-e-depois → ROI de produção baixo, frustração latente."),
            ("Sensação de estar abaixo do que merece", "14 anos, preceptora, formação UFPR + PUC + IPOG — currículo de Águia comunicado como Pato. Síndrome do impostor comercial mascarada de 'humildade'."),
        ],
        "gaps": [
            ("Posicionamento", "'Rinoplastia natural' é commodity em IG. Falta promessa quantificável + inimigo declarado + ICP nominal."),
            ("Comercial", "Zero avaliações no Doctoralia depois de 14 anos é colapso de prova social digital. Nem coleta review."),
            ("Monetização", "Estrutura espalhada (consultório + 3 hospitais + auditoria + docência) = clássico 'operário do bisturi' rodando muito pra ganhar mediano. Auditoria municipal é âncora típica de quem segura emprego CLT por medo do particular."),
        ],
        "hooks_abertura": [
            "Tatiana, antes de começar — 14 anos de carreira, formação UFPR e PUC, preceptora de residência, faz rinoplastia. E tem 9 mil seguidores e zero avaliação no Doctoralia. Não é falta de competência. É falta de quê, na sua leitura?",
            "A gente leu seu site. 'Beleza natural sem mudar drasticamente' é o que 800 outros otorrinos com rinoplastia falam. Se a gente pegasse seu Instagram e tirasse o nome, dava pra adivinhar que é você?",
            "Auditora da Prefeitura, preceptora, atende São Vicente, Marcelino, Novaclínica, tem consultório próprio E faz rinoplastia. Quando alguém te pergunta 'o que você faz?', qual é a resposta que sai primeiro?",
        ],
        "objecoes_esperadas": [
            "'Já tenho minha estrutura montada'",
            "'Marketing agressivo não combina com otorrino sério'",
            "'Curitiba é um mercado conservador, paciente busca técnica não show'",
        ],
        "abordagem_recomendada": "Tom firme + espelho duro. Ela é Gavião com casca de Pato — sabe que precisa, mas tem casca de medicina séria. Patrick: pinçar a contradição entre estrutura e resultado. Mateus: trazer caso de outra otorrino-rinoplastista que reposicionou e dobrou ticket.",
        "alerta_homonimo": "97% confiança. CUIDADO: irmã Isabella Mauad Patruni também é médica em Curitiba (cirurgiã geral). Tatiana = otorrino. Não confundir.",
        "fontes": [
            "https://dratatianapatruni.com.br/",
            "https://www.doctoralia.com.br/tatiana-mauad-patruni/otorrino/curitiba",
            "https://saovicentecuritiba.com.br/profissionais/tatiana-mauad-patruni/",
            "https://www.escavador.com/sobre/10851668/tatiana-mauad-patruni",
            "https://www.instagram.com/dratatianapatruni/",
        ],
    },
    {
        "slug": "rafael-bozzo-tacino",
        "ordem": 2,
        "hora": "12:00",
        "zoom": "https://us06web.zoom.us/j/83011506773",
        "nome": "Dr. Rafael Bozzo Tacino",
        "nome_lista": "Dr Rafael Bozzo",
        "correcao_grafia": None,
        "especialidade": "Urologia",
        "subespecialidade": "Uro-Oncologia · Cirurgia Robótica (Da Vinci) · Endourologia · Laparoscopia · Litíase",
        "cidade": "Ribeirão Preto",
        "estado": "SP",
        "crm": "CRM-SP 108598 · RQE 35241",
        "formacao": [
            "FMRP-USP — graduação e residência em Urologia",
            "Mestrado FMRP-USP (2015) — finasterida e PSA em jovens",
            "Fellowship Memorial Sloan-Kettering Cancer Center (NY) — Uro-Oncologia + Cirurgia Robótica",
            "Certificação Intuitive Surgical (Da Vinci)",
        ],
        "estruturas": [
            "Médico Assistente HC FMRP-USP — chefe do setor de Urologia Oncológica",
            "Tacino Urologia — Av. Antônio Diederichsen, 400 · Metropolitan Business Center · Jardim América",
            "Hospital São Lucas Ribeirão Preto",
        ],
        "credenciais": [
            "Membro Titular SBU (TiSBU)",
            "Membro Endourological Society",
            "Banca de mestrado FMRP",
            "Cirurgião Robótico certificado Da Vinci",
            "Fellowship internacional em Sloan-Kettering",
        ],
        "instagram": "@dr.rafael.tacino.uro",
        "instagram_url": "https://www.instagram.com/dr.rafael.tacino.uro/",
        "instagram_aberto": True,
        "instagram_seguidores": "~9.500",
        "instagram_posts": "ativo desde 2023",
        "instagram_bio": '"Dr Rafael Tacino - Urologia"',
        "instagram_tom": "Educacional clínico — urologia, saúde sexual masculina, prevenção. Tom professoral, sem rosto-protagonista, sem CTA, sem oferta",
        "site": "https://www.tacinourologia.com.br/",
        "doctoralia": "https://www.doctoralia.com.br/rafael-bozzo-tacino/urologista/ribeirao-preto",
        "linkedin": None,
        "tagline_atual": '"Cirurgia de Excelência"',

        "posicionamento_atual_publico": "Urologista oncológico de elite acadêmica (USP + Sloan-Kettering) que oferece cirurgia robótica de excelência — comunicado em tom institucional de hospital universitário.",
        "potencial_publico": "Rafael, você carrega no currículo aquilo que mentoria nenhuma constrói: <strong>USP + Sloan-Kettering + Da Vinci + 100% particular</strong>. O ponto de virada não é o que você sabe — é arquitetar uma marca que cobre proporcional ao que você já é. Sair de operador da própria agenda para arquiteto de um sistema que escala.",

        "perfil_cpp": "ÁGUIA",
        "score_compra": 84,
        "perfil_evidencias": [
            "100% particular declarado · consulta R$400 (Doctoralia)",
            "13 reviews 5 estrelas",
            "FMRP-USP + Memorial Sloan-Kettering — top 1% Brasil",
            "Chefe de setor HC-USP-RP",
            "Site profissional + IG ativo + endereço Metropolitan Business Center",
        ],
        "dores_top3": [
            ("Estagnação + ticket abaixo do repertório técnico", "Sloan-Kettering no currículo, R$400 a consulta em RP. Os dois números não conversam."),
            ("Dependência de hospital + indicação acadêmica", "Toda tração vem do HC e do encaminhamento USP — sem entrada autônoma de paciente particular pago. IG dormente, site institucional."),
            ("Síndrome do impostor comercial", "Perfil USP/Sloan tende a separar 'medicina séria' de 'vendas'. Vende excelência genérica, não o nicho craveado (câncer de próstata robótico)."),
        ],
        "gaps": [
            ("Marca pessoal", "Nenhum sistema de conteúdo, nenhuma promessa, nenhuma diferenciação além do diploma. Vende 'cirurgia de excelência' (genérico) quando poderia ser 'o uro-oncologista de Ribeirão treinado em Sloan-Kettering'."),
            ("Comercial", "Sem processo, sem script, sem qualificação, sem ancoragem de preço, sem fechamento. Tabela cirúrgica provavelmente reativa."),
            ("Escala", "Posicionamento ainda 100% individual. Sem produto, sem programa, sem fila de espera. Receita travada nas próprias horas."),
        ],
        "hooks_abertura": [
            "Rafael, você é o cara que pegou Sloan-Kettering e voltou pra Ribeirão. Em quantos pacientes particulares por mês isso está se traduzindo hoje — e quanto você acha que deveria estar?",
            "R$400 a consulta. Sloan-Kettering no currículo. Olha pra esses dois números e me diz se eles conversam.",
            "Abri seu Instagram. 9,5 mil seguidores, último post em dezembro. Você está deixando dinheiro e autoridade na mesa por escolha ou por travamento?",
        ],
        "objecoes_esperadas": [
            "'Já sou particular, já sou referência'",
            "'R$38-42k pra que se já tenho o que CPP promete?'",
            "'Marketing não combina com perfil acadêmico-cirúrgico'",
        ],
        "abordagem_recomendada": "Tom peer-to-peer (NUNCA 'aprenda do zero'). Patrick: 'Você venceu a fase 1. Está na fase 2: virar marca'. CUIDADO: não tratar como Pato/Urubu — ele se ofende. Lead de mais alto valor potencial do dia. Considerar entrada como case ou versão premium da mentoria.",
        "alerta_homonimo": "95% confiança. Sobrenome 'Bozzo Tacino' é raro. Único urologista no Brasil com esse nome.",
        "fontes": [
            "https://www.tacinourologia.com.br/",
            "https://tacino.site.med.br/",
            "https://www.doctoralia.com.br/rafael-bozzo-tacino/urologista/ribeirao-preto",
            "https://www.instagram.com/dr.rafael.tacino.uro/",
            "https://teses.usp.br/teses/disponiveis/17/17137/tde-02022016-093721/publico/RafaelBozzoTacinoOrig.pdf",
        ],
    },
    {
        "slug": "paulo-victor-pereira",
        "ordem": 3,
        "hora": "13:00",
        "zoom": "https://us06web.zoom.us/j/88042216514",
        "nome": "Dr. Paulo Victor de Souza Pereira",
        "nome_lista": "Dr Paulo Victor Pereira",
        "correcao_grafia": "Patrick listou como 'Paulo Victor Pereira'. Nome completo confirmado pela base de inscritos: Paulo Victor DE SOUZA Pereira. Sobrenome materno 'de Souza' explica por que não indexava — é o conector que confirma identidade.",
        "especialidade": "Ortopedia e Traumatologia",
        "subespecialidade": "Cirurgia do Pé e Tornozelo · Medicina da Dor · Ortopedia Geral",
        "cidade": "Brasília",
        "estado": "DF",
        "crm": "CRM-DF 22186 · RQE 17862",
        "formacao": [
            "Especialista em Ortopedia e Traumatologia · RQE 17862",
            "Subespecialização em Cirurgia do Pé e Tornozelo",
            "[Faculdade e residência específicas: a confirmar na call]",
        ],
        "estruturas": [
            "ICOD — Instituto da Coluna Vertebral, Ortopedia, Dor e Otorrino · Águas Claras (Albany Medical Center, R. 05 Norte Lt 03 Loja 06)",
            "ICOD Paranoá — Área Especial Qd 02 Cj K · 71570-200",
            "Sócio fundador da ICOD desde 2018 (CNPJ 30.599.744/0001-35) · 10 sócios",
        ],
        "credenciais": [
            "Doctoralia: 151 avaliações verificadas · média 5 estrelas",
            "7 anos como sócio fundador de clínica multidisciplinar ortopédica",
            "2 endereços de atendimento — Águas Claras (premium) + Paranoá (popular)",
            "Aceita 54+ convênios — Postal Saúde, Camed, Saúde Caixa (Brasília funcionalismo público)",
        ],
        "instagram": None,
        "instagram_url": None,
        "instagram_aberto": False,
        "instagram_seguidores": None,
        "instagram_posts": None,
        "instagram_bio": "[sem perfil pessoal — só vinculado a @clinicaicod institucional]",
        "instagram_tom": "Ausente como marca pessoal. Depende 100% do tráfego do Doctoralia e da marca da clínica.",
        "site": "https://icod.com.br/",
        "doctoralia": "https://www.doctoralia.com.br/paulo-victor-de-souza-pereira/ortopedista-traumatologista/aguas-claras",
        "linkedin": None,
        "tagline_atual": "[sem narrativa pública pessoal — diluído na marca ICOD]",

        "posicionamento_atual_publico": "Ortopedista de pé e tornozelo dentro de uma clínica multidisciplinar respeitada (ICOD) em Águas Claras — reputação técnica construída via Doctoralia (151 reviews 5 estrelas), mas a voz própria ainda está dentro da marca dos 10 sócios.",
        "potencial_publico": "Paulo Victor, você já fez o trabalho difícil — 7 anos construindo a ICOD com 9 outros sócios, 151 avaliações 5 estrelas, presença em Águas Claras e Paranoá. <strong>Reputação clínica está cravada.</strong> A pergunta agora é outra: como o paciente premium de Brasília te encontra <em>antes</em> de procurar a clínica? Como sua autoridade individual sai do guarda-chuva da marca coletiva?",

        "perfil_cpp": "GAVIÃO em transição (com aroma de Pato residual)",
        "score_compra": None,
        "perfil_evidencias": [
            "Pagou R$1.000 sinal — compromisso financeiro real, busca mentoria premium",
            "Sócio fundador ICOD = já entendeu o jogo do negócio",
            "151 reviews 5 estrelas Doctoralia = autoridade clínica cravada",
            "MAS consulta R$350 num bairro premium de Brasília = subprecificação clássica",
            "Aceita 54+ convênios incluindo Postal Saúde / Camed / Saúde Caixa = ainda dependente de tabela",
            "Sem Instagram pessoal, sem site próprio, sem LinkedIn = invisível como marca individual",
        ],
        "dores_top3": [
            ("Convênio com ticket comprimido", "54+ planos aceitos + R$350 particular num condomínio premium de Águas Claras. Margem espremida, agenda lotada de consulta, cirurgia paga via tabela CBHPM. Postal/Camed/Saúde Caixa = funcionalismo público de Brasília."),
            ("Diluição dentro da sociedade ICOD", "10 sócios numa marca posicionada genericamente como 'coluna, ortopedia, dor e otorrino'. Ele é invisível dentro da própria clínica que ajudou a fundar. Sem autoridade individual = sem ticket próprio."),
            ("Sem marca pessoal", "Em 2026, ortopedista de pé/tornozelo em Brasília sem Instagram pessoal, sem site, sem LinkedIn. Provável crença: 'Doctoralia + boca-a-boca basta'. É exatamente a crença que CPP quebra."),
        ],
        "gaps": [
            ("Sem nicho dentro do nicho", "'Pé e tornozelo' é amplo. Não comunica se foca hálux valgo? Esporão? Lesão esportiva? Pé diabético? Essa escolha dor-a-dor é o que separa autoridade de commodity."),
            ("Sem prova social fora do Doctoralia", "151 reviews só na plataforma. Não converte para particular premium porque paciente Gavião/Águas Claras pesquisa Instagram antes de pagar R$350+."),
            ("Sem produto próprio / jornada", "Consulta avulsa CBHPM. Não há pacote, programa, jornada de tratamento, retorno estruturado — modelo Pato dentro de estrutura Gavião."),
        ],
        "hooks_abertura": [
            "Paulo Victor, 7 anos como sócio fundador da ICOD, 151 avaliações 5 estrelas, dois endereços em Brasília. Esse é o caso clássico de quem construiu reputação clínica e ainda não traduziu isso em negócio. Concorda?",
            "Eu fiz uma pesquisa sobre você e achei tudo: CRM, ICOD, Doctoralia, Paranoá, Águas Claras. Sabe o que eu não achei? Você. Não tem Instagram, não tem site, não tem LinkedIn. Quem é você fora da clínica que você dividiu com 9 pessoas?",
            "R$350 a consulta particular, num condomínio premium de Águas Claras, aceitando Postal Saúde e Camed. Me explica como o seu ticket virou esse — e o que você acha que está te impedindo de cobrar R$800, R$1.200?",
        ],
        "objecoes_esperadas": [
            "'Brasília tem cultura de funcionalismo público — paciente quer usar Postal/Camed'",
            "'Eu não preciso de Instagram, meu Doctoralia me trouxe 151 reviews'",
            "'Como saio da marca ICOD se ajudei a construir e tenho 9 sócios?'",
            "'Cirurgião sério não precisa aparecer'",
        ],
        "abordagem_recomendada": "Tom de espelho preciso. Patrick: 'Você é caso de sucesso clínico que ainda não virou negócio'. NÃO atacar a ICOD — usar como ativo. Mostrar como cirurgião premium em Brasília cobra R$1.500 consulta + R$80-120k cirurgia particular puro mantendo participação na clínica. Pé/tornozelo em DF tem vibe esportiva (corredores, ciclistas, classe alta) que paga premium se houver ângulo. Mateus traz caso prático.",
        "alerta_homonimo": "97% confiança. CRM-DF 22186 + RQE 17862 + nome completo (Paulo Victor de Souza Pereira) + Brasília + sócio CNPJ ICOD + Doctoralia + DDD 61 — tudo bate. Único gap remanescente: formação acadêmica específica (faculdade + residência) e Instagram pessoal — usar como pergunta na call para gerar conexão.",
        "fontes": [
            "https://www.doctoralia.com.br/paulo-victor-de-souza-pereira/ortopedista-traumatologista/aguas-claras",
            "https://icod.com.br/",
            "https://cnpj.biz/30599744000135",
            "https://www.albanymedical.com.br/ortopedia-aguas-claras/icod-instituto-da-coluna-ortopedia-e-dor/",
            "https://www.instagram.com/clinicaicod/",
        ],
    },
    {
        "slug": "tarik-soares-suleiman",
        "ordem": 4,
        "hora": "14:00",
        "zoom": "https://us06web.zoom.us/j/89649935942",
        "nome": "Dr. Tarik Soares Suleiman",
        "nome_lista": "Dr Tarick Soares",
        "correcao_grafia": "Patrick listou como 'Tarick' (com C). Grafia oficial em CRM, site, Escavador e Receita: TARIK (sem C).",
        "especialidade": "Cirurgia do Aparelho Digestivo",
        "subespecialidade": "Cirurgia Bariátrica e Metabólica · Vesícula · Hérnias · Refluxo (Videolaparoscopia Avançada)",
        "cidade": "Araguaína",
        "estado": "TO",
        "crm": "CRM-TO 4068 · RQE 2506",
        "formacao": [
            "Medicina ITPAC Araguaína (2012)",
            "Residência Cirurgia Geral — Hospital Dr. Carlos Macieira / SES-MA (2014)",
            "Residência Cirurgia do Aparelho Digestivo — HU Presidente Dutra / UFMA (2018)",
            "Fellowship Videolaparoscopia Avançada — Hospital Adventista Silvestre · RJ (2019)",
        ],
        "estruturas": [
            "Hospital São Lucas — Rua 13 de Maio, 840 · Centro · Araguaína",
            "Hospital Regional de Araguaína (HRA) — opera bariátrica",
            "Unimed Araguaína — corpo clínico credenciado",
            "Sócio do ICOD — Instituto de Cirurgia de Obesidade e Diabetes (CNPJ 37.320.580/0001-04)",
        ],
        "credenciais": [
            "Dupla residência (Cirurgia Geral + Aparelho Digestivo) + Fellowship Videolaparoscopia",
            "Publicação no ABCD - Arquivos Brasileiros de Cirurgia Digestiva (2019)",
            "Sócio-fundador de instituto especializado (ICOD)",
            "Cirurgião referência regional norte do Tocantins",
        ],
        "instagram": "@drtariksuleiman ✓ (verificado)",
        "instagram_url": "https://www.instagram.com/drtariksuleiman/",
        "instagram_aberto": True,
        "instagram_seguidores": "31,6 mil",
        "instagram_posts": "816",
        "instagram_bio": '"Dr. Tarik | Cirurgião de vesícula | Araguaína - Tocantins" — bio expandida: "Ajudo você a perder o medo e recuperar a liberdade de comer. Vesícula | Videolaparoscopia | CRMTO4068 | RQE2506"',
        "instagram_tom": "Educativo + emocional. Bio com ÂNGULO PRO PACIENTE (não pro médico): 'liberdade de comer'. Posicionamento de mercado claro: cirurgião DA VESÍCULA. Mateus já segue.",
        "site": "https://tariksuleiman.com.br/oficial",
        "doctoralia": None,
        "linkedin": "https://www.linkedin.com/in/tarik-soares-suleiman-588a4a111/",
        "tagline_atual": '"Ajudo você a perder o medo e recuperar a liberdade de comer"',

        "posicionamento_atual_publico": "Cirurgião de vesícula com 31,6k seguidores em Araguaína-TO — verificado azul, narrativa cravada ('liberdade de comer'), posicionamento de nicho que poucos têm em qualquer cidade do Brasil. Sobrenome único (Suleiman) é ativo de memória local.",
        "potencial_publico": "Tarik, é raro encontrar um cirurgião que já tenha feito tanto certo: <strong>31,6 mil seguidores, ângulo cravado ('liberdade de comer'), site próprio, instituto, fellowship em videolaparoscopia avançada</strong>. A pergunta não é mais 'o que falta construir'. É: <strong>como transformar tudo isso num programa premium</strong> que cobra pelo nome e não pelo procedimento? Cirurgia de vesícula deixa de ser uma operação e vira a entrada de uma jornada PREMIUM.",

        "perfil_cpp": "ÁGUIA digital (mais avançado do que a base estimou)",
        "score_compra": 78,
        "perfil_evidencias": [
            "31,6 MIL seguidores no Instagram + verificado azul · 816 posts · Mateus já segue ele",
            "Bio com ÂNGULO PRO PACIENTE ('liberdade de comer') — método PREMIUM rascunhado intuitivamente",
            "Posicionamento cravado: 'CIRURGIÃO DE VESÍCULA' (não bariátrica genérica)",
            "Site próprio com domínio tariksuleiman.com.br/oficial",
            "Sócio do ICOD Araguaína — instituto especializado obesidade/diabetes",
            "RQE 2506 + Fellowship Videolaparoscopia avançada (Adventista Silvestre RJ)",
        ],
        "dores_top3": [
            ("Convênio + ticket comprimido", "Unimed Araguaína e HRA dominam volume bariátrico. Tabela Unimed para bariátrica no interior é baixa, e HRA é SUS/regulação."),
            ("Sem marca pessoal forte / posicionamento técnico = invisível no particular", "Site é cartão de visitas com lista de procedimentos, sem narrativa, sem promessa, sem ICP claro. Sem amplificação digital nacional."),
            ("Mercado pequeno + concorrência viral de capital", "Bariátrica em Araguaína concorre com cirurgiões de Palmas, Goiânia, Brasília que aparecem mais. Cirurgião do interior com bom CV + nenhum tráfego digital = teto de fila baixo."),
        ],
        "gaps": [
            ("Oferta", "Vende 'vesícula, hérnia e refluxo' (procedimento) em vez de resultado/transformação para um ICP específico. Não há ticket premium estruturado."),
            ("Máquina", "Zero indício de funil de captação particular — sem lead magnet, sem fluxo de pré-consulta. Volume vem do convênio e do hospital."),
            ("Identidade comercial", "Sócio de 4 num instituto, divide marca com ICOD em vez de construir 'Dr. Tarik Suleiman' como ativo individual."),
        ],
        "hooks_abertura": [
            "Tarik, você tem CV de cirurgião de capital trabalhando em Araguaína. Por que sua agenda particular não reflete isso?",
            "Você abriu o ICOD em 2020 com 3 sócios. Em 5 anos, quanto da sua receita hoje vem do particular fora do convênio?",
            "Quando alguém em Tocantins precisa do melhor cirurgião pra vesícula complicada, eles pensam em você ou no hospital?",
        ],
        "objecoes_esperadas": [
            "'Tocantins não paga ticket de capital'",
            "'Já faço bariátrica no São Lucas, agenda boa'",
            "'Mentoria de SP/Sul não serve pro interior do Norte'",
        ],
        "abordagem_recomendada": "Tom técnico + ambicioso. Dor: 'você construiu tudo certo — só que ainda está cobrando preço de Tocantins'. Mostrar como bariátrico do interior cobra R$45-60k particular puro vendendo PROCESSO (consultoria + cirurgia + acompanhamento), não procedimento. Bariátrica como produto premium, não como cirurgia.",
        "alerta_homonimo": "80% confiança. Sobrenome único (origem árabe). Confirmação tripla: nome+CRM-TO 4068+especialidade digestivo+cidade Araguaína. Verificar autonomia comercial dele dentro do ICOD (4 sócios podem travar marca pessoal).",
        "fontes": [
            "https://drtariksuleiman.com/",
            "https://www.linkedin.com/in/tarik-soares-suleiman-588a4a111/",
            "https://www.instagram.com/drtariksuleiman/",
            "https://www.escavador.com/sobre/9766774/tarik-soares-suleiman",
            "ABCD - Arquivos Brasileiros de Cirurgia Digestiva (2019)",
        ],
    },
    {
        "slug": "julio-fran",
        "ordem": 5,
        "hora": "15:00",
        "zoom": "https://us06web.zoom.us/j/84726454172",
        "nome": "Dr. Júlio Fran da Silva Pinto",
        "nome_lista": "Dr Júlio Fran",
        "correcao_grafia": "Nome completo descoberto na base: Júlio Fran da Silva Pinto. 'Fran' é nome civil, não abreviação.",
        "especialidade": "Ortopedia e Traumatologia",
        "subespecialidade": "Ortopedia Pediátrica",
        "cidade": "Timbó",
        "estado": "SC",
        "crm": "CRM-SC 24030",
        "formacao": [
            "Especialista em Ortopedia e Traumatologia (TEOT)",
            "Subespecialização em Ortopedia Pediátrica",
        ],
        "estruturas": [
            "Consultório próprio — Rua Bolívia, 148 sala 206 · bairro Imigrantes · Timbó-SC",
            "Hospital e Maternidade Oase — Timbó-SC",
            "Atende Unimed",
        ],
        "credenciais": [
            "TEOT — Sociedade Brasileira de Ortopedia e Traumatologia",
            "Subespecialização em Ortopedia Pediátrica (nicho raro no Vale do Itajaí)",
            "Corpo clínico Hospital e Maternidade Oase",
        ],
        "instagram": "@drjuliofran",
        "instagram_url": "https://www.instagram.com/drjuliofran/",
        "instagram_aberto": False,
        "instagram_seguidores": "—",
        "instagram_posts": "—",
        "instagram_bio": "[provavelmente privado ou recém-aberto — não indexa]",
        "instagram_tom": "Inativo / privado",
        "site": None,
        "doctoralia": None,
        "linkedin": None,
        "tagline_atual": None,

        "posicionamento_atual_publico": "Ortopedista pediátrico com consultório próprio em Timbó/SC — um dos poucos do Vale do Itajaí com a subespecialidade. Escassez técnica é o ativo natural; falta sistema digital que comunique.",
        "potencial_publico": "Júlio, você ocupa uma posição rara: <strong>ortopedista pediátrico em uma cidade que dificilmente tem outro</strong>. A escassez já te protegeu por anos — e por isso você não precisou se vender. Mas isso é também o seu teto. O próximo capítulo é virar referência <strong>estadual</strong>, não só municipal.",

        "perfil_cpp": "URUBU com tração latente de Gavião",
        "score_compra": 45,
        "perfil_evidencias": [
            "Consultório próprio + nicho pediátrico + 1 hospital",
            "Sem site, sem Doctoralia, sem Instagram público forte",
            "Atende Unimed (convênio dominante na agenda)",
            "DDD 11 (SP) no celular vs prática SC = origem provável SP, capital pode ser maior do que aparenta",
            "Pagou R$1k de sinal = sinaliza ambição econômica",
        ],
        "dores_top3": [
            ("Cidade pequena + ticket comprimido pelo convênio", "Timbó tem ~46k habitantes. Unimed domina pediatria — ticket pago é baixo, e SUS regula resto."),
            ("Sem qualquer marketing digital", "Invisível no Google sob o nome. Pais que poderiam pagar particular não acham — vão pra ortopedista pediátrico de Joinville/Floripa que aparece."),
            ("Teto regional bloqueado pela falta de sistema de comunicação", "Subespecialidade rara é ativo escondido. Sem narrativa pública, a escassez não vira preço."),
        ],
        "gaps": [
            ("Identidade digital", "Sem site nem perfil indexado. Mãe de classe média alta busca no Instagram antes de marcar — e não acha."),
            ("Posicionamento de nicho", "'Ortopedista pediátrico do Vale do Itajaí' é categoria existente que ele não está ocupando publicamente."),
            ("Funil comercial", "Nenhum ponto de captura (link, WhatsApp Business, formulário). Toda agenda é receptiva via convênio."),
        ],
        "hooks_abertura": [
            "Júlio, antes de tudo — você é o ortopedista PEDIÁTRICO de Timbó, certo? Quero confirmar porque é raríssimo achar um no Vale do Itajaí.",
            "Vi que seu Instagram está fechado. Isso é decisão consciente ou é uma das coisas que você quer destravar com a CPP?",
            "Você pagou sinal antes da call. Isso me diz que tem dinheiro entrando. Me conta: o problema é faturamento, margem ou cansaço — qual desses é o que mais te tira o sono hoje?",
        ],
        "objecoes_esperadas": [
            "'Em Timbó não tem mercado pra particular premium'",
            "'Pais querem convênio, não particular'",
            "'Ortopedia pediátrica é serviço público, mães não pagam R$1500'",
            "'CPP é caro pra realidade do interior'",
        ],
        "abordagem_recomendada": "Tom de convicção + caso real. Mostrar mentorados CPP do interior que viraram particular puro. ROI: 1 cirurgia ortopédica pediátrica particular paga 1/3 do CPP. Falar parcelamento longo. CUIDADO com qualificação financeira — pode ser Pato fingindo Gavião.",
        "alerta_homonimo": "Match único confirmado: CRM-SC 24030, Timbó, ortopedia pediátrica. Sem ambiguidade.",
        "fontes": [
            "https://agendaconvenio.com/unimed/timbo/julio-fran-da-silva-pinto",
            "https://hospitaloase.com.br/profissionais/",
            "https://www.instagram.com/drjuliofran/",
        ],
    },
    {
        "slug": "marina-marangon-melhado",
        "ordem": 6,
        "hora": "16:00",
        "zoom": "https://us06web.zoom.us/j/82606867642",
        "nome": "Dra. Marina Marangon Melhado",
        "nome_lista": "Dra Mariana Marangon",
        "correcao_grafia": "Patrick listou como 'Mariana'. Nome correto em CRM, site, CNN, Correio Braziliense: MARINA.",
        "especialidade": "Ortopedia e Traumatologia",
        "subespecialidade": "Cirurgia do Pé e Tornozelo · Medicina Esportiva · Ortopedia Integrativa (Nutrologia + Hormônios + Regenerativa)",
        "cidade": "São Paulo",
        "estado": "SP",
        "crm": "CRM-SP 179.632 · CRM-MT 7454 · RQE 121.033",
        "formacao": [
            "Medicina UNIC Cuiabá",
            "Residência Ortopedia — Beneficência Portuguesa de Ribeirão Preto",
            "Pós Nutrologia — Uningá + Plenitude",
            "Pós Nutrição Esportiva + Medicina Estética",
            "Certificações em hormonologia + terapias EV/IM",
        ],
        "estruturas": [
            "Clínica AGHA — R. Bento de Andrade, 436 · Jardim Paulista · SP",
            "Sala secundária — R. Joaquim Floriano, 413 · 9º andar · Itaim Bibi",
            "100% PARTICULAR — não aceita convênios",
        ],
        "credenciais": [
            "Colunista CNN Brasil (Saúde)",
            "Colunista Correio Braziliense (Radar)",
            "Fonte recorrente THMais / NovaBrasil",
            "Múltiplas matérias mainstream em 2025 (artrose, fascite, joanete, longevidade)",
        ],
        "instagram": "@dramarinamelhado ✓ (verificado azul)",
        "instagram_url": "https://www.instagram.com/dramarinamelhado/",
        "instagram_aberto": True,
        "instagram_seguidores": "100",
        "instagram_posts": "14",
        "instagram_bio": '"Cirurgia do Pé e Tornozelo e Regenerativa, São Paulo-SP" — bio expandida: "Ajudo pessoas com dores musculoesqueléticas a retomarem sua rotina, seus movimentos e o prazer de viver sem dor."',
        "instagram_tom": "PERFIL RECÉM-ABERTO/MIGRADO — apenas 14 posts e 100 seguidores apesar de selo azul. Tom limpo, ângulo do paciente ('prazer de viver sem dor'). Endereço Rua Bento de Andrade 436.",
        "site": "https://www.dramarinamelhado.com.br/",
        "doctoralia": "https://www.doctoralia.com.br/marina-marangon-melhado/ortopedista-traumatologista/sao-paulo",
        "linkedin": None,
        "tagline_atual": '"Viver com dor não precisa ser o seu normal"',

        "posicionamento_atual_publico": "Ortopedista integrativa que trata dor crônica como sintoma sistêmico — junta cirurgia do pé/tornozelo, hormônios, nutrologia e regenerativa pra devolver performance.",
        "potencial_publico": "Marina, autoridade técnica você já tem. CNN, Correio, Jardim Paulista, particular puro, narrativa diferenciada. <strong>O próximo movimento não é construir — é arquitetar.</strong> Transformar agenda lotada em império com agenda <em>limitada</em> e ticket assimétrico. Virar categoria, não competidora.",

        "perfil_cpp": "ÁGUIA",
        "score_compra": 84,
        "perfil_evidencias": [
            "100% particular puro — zero convênio (sinal mais forte)",
            "Endereço Jardim Paulista + Itaim (territórios elite SP)",
            "Mídia tier-1: CNN, Correio Braziliense, THMais",
            "Verificado azul no Instagram (selo de autoridade)",
            "MAS apenas 100 seguidores e 14 posts no @dramarinamelhado — perfil RECÉM-ABERTO/migrado",
            "Mudou MT→SP buscando outro nível — comportamento de Águia em escala",
        ],
        "dores_top3": [
            ("Autoridade externa GIGANTE, audiência interna ZERADA", "Verificada no IG, CNN, Correio Braziliense, mas só 100 seguidores e 14 posts no perfil atual. Esse delta é a dor pública mais visível: a CNN abriu a porta, mas ela não tem casa para receber a visita."),
            ("Teto invisível / dor de identidade", "Já é referência técnica em SP, mas a marca pessoal não acompanhou. Cobra abaixo do que entrega. Fome de virar 'a Dra. Ana Hirsch da ortopedia integrativa'."),
            ("Sem produto digital nem fila blindada", "Particular puro sem convênio = se a panela de leads esfria, agenda cai. Sem produto, sem método nomeado, sem programa de continuidade."),
        ],
        "gaps": [
            ("Audiência própria descolada da autoridade", "Selo azul + CNN + Correio + 100 seguidores não convivem bem. Esse é o gap número um — a casa precisa caber a visita."),
            ("Método proprietário", "Faz ortopedia integrativa, mas não tem nome próprio do protocolo. Vira commodity premium em vez de categoria."),
            ("Site/funil sub-aproveitado", "Página com placeholders ('555-555-5555' e 'meuemail@email.com.br') — template não-customizado. Funil quebrado, ticket abaixo do potencial (R$300 em Jardim Paulista)."),
        ],
        "hooks_abertura": [
            "Marina, abri seu Instagram agora. Selo azul. CNN. Correio Braziliense. E 100 seguidores. Esses três dados não conversam. Conta pra mim o que aconteceu.",
            "Você é uma das poucas ortopedistas em SP com mídia tier-1 e selo de verificação. E a sua casa digital cabe em 14 posts. O que está te travando entre a autoridade externa e a audiência própria?",
            "R$300 a consulta em Jardim Paulista, sendo entrevistada na CNN. Se a gente tirar o convênio da equação — porque você já saiu — o que sobra pra explicar esse ticket?",
        ],
        "objecoes_esperadas": [
            "'Já sou particular pura, já tenho mídia (CNN), o que CPP me dá?'",
            "'Já faço marketing, R$38k é investimento alto pra ROI marginal'",
            "'Quero entender se vocês atendem nível elite ou é básico'",
        ],
        "abordagem_recomendada": "Tom elite-para-elite. NÃO vender 'sair do convênio' (já saiu). Vender ESCALA E PERPETUAÇÃO: agenda lotada → produto digital, expansão para outras capitais, fila de espera, ticket 5-15k/consulta. Patrick abre com case de Águia que aplicou CPP e dobrou ticket. Tom sem afago, ela testa profundidade.",
        "alerta_homonimo": "90% confiança. Nome composto único. Sem ambiguidade. Risco residual: ser Gavião-com-discurso-de-Águia (verificar quanto fatura/mês na call).",
        "fontes": [
            "https://www.dramarinamelhado.com.br/",
            "https://www.doctoralia.com.br/marina-marangon-melhado/ortopedista-traumatologista/sao-paulo",
            "https://www.cnnbrasil.com.br/saude/joelho-travado-dor-pode-ser-sinal-precoce-de-artrose/",
            "https://www.correiobraziliense.com.br/cbradar/dra-marina-melhado-ortopedista-como-aliviar-a-dor-da-fascite-plantar-de-forma-segura/",
        ],
    },
    {
        "slug": "eduardo-watanabe-castanheira",
        "ordem": 7,
        "hora": "17:00",
        "zoom": "https://us06web.zoom.us/j/82920171401",
        "nome": "Dr. Eduardo Watanabe Castanheira",
        "nome_lista": "Dr Eduardo Watanabe",
        "correcao_grafia": None,
        "especialidade": "Ortopedia e Traumatologia",
        "subespecialidade": "Cirurgia da Mão (microcirurgia reconstrutiva)",
        "cidade": "Patos de Minas",
        "estado": "MG",
        "crm": "CRM-MG 27899 · RQE 12516 (Ortopedia) · RQE 12515 (Cirurgia da Mão)",
        "formacao": [
            "Medicina FCMMG (1989-1994)",
            "Residência Ortopedia/Traumatologia — Hospital Ortopédico BH (1995-1997)",
            "Fellowship Cirurgia da Mão (1998) — sob Dr. Arlindo Pardini",
            "MBA Gestão Empresarial — FGV",
            "MBA Gestão de Saúde — FGV",
        ],
        "estruturas": [
            "Consultório próprio — R. Padre Caldeira, 386 · Centro · Patos de Minas",
            "Hospital Nossa Senhora de Fátima (HNSF) — corpo clínico",
            "Hospital Regional Antônio Dias",
            "CNPJ próprio — Eduardo Watanabe Castanheira Eireli (30.590.217/0001-60)",
        ],
        "credenciais": [
            "Membro Titular SBOT",
            "Membro Titular Sociedade Brasileira de Cirurgia da Mão",
            "Membro Titular Sociedade Brasileira de Medicina Hiperbárica",
            "Duplo MBA FGV",
            "30 anos de carreira · referência regional Triângulo Mineiro/Alto Paranaíba",
            "Único cirurgião de mão titulado da macrorregião",
        ],
        "instagram": "@dr.eduardowatanabe",
        "instagram_url": "https://www.instagram.com/dr.eduardowatanabe/",
        "instagram_aberto": True,
        "instagram_seguidores": "6.808",
        "instagram_posts": "672",
        "instagram_bio": '"Dr. Eduardo Watanabe - Ortopedista e Traumatologista" — bio expandida: "Cirurgia da Mão | CRM MG 27899 | RQE 12516 | RQE 12515 | @hnsfoficial @norte.hnsf | Rua Padre Caldeira, 386, Patos de Minas"',
        "instagram_tom": "Educativo (túnel do carpo, dedo em gatilho, Dupuytren). Tom institucional, professoral, sem rosto-protagonista. 672 posts e só 6.808 seguidores = 10 seguidores por post (ROI de conteúdo baixo).",
        "site": "https://eduardoortopedia.com.br/",
        "doctoralia": "https://www.catalogo.med.br/doutor/eduardo-watanabe-castanheira-1870802.htm",
        "linkedin": None,
        "tagline_atual": '"Estruturas tão complexas quanto as mãos exigem cuidado especializado"',

        "posicionamento_atual_publico": "Especialista técnico em mão de Patos de Minas — credenciais e didática. Vende competência, não desejo. Referência consolidada boca-a-boca em comunidade de ~150k habitantes.",
        "potencial_publico": "Doutor Eduardo, 30 anos de carreira, formação com Arlindo Pardini, titular em 3 sociedades, referência histórica do Alto Paranaíba. <strong>O capítulo agora é outro.</strong> Não é construir do zero — é decidir o que vai deixar quando parar. Como monetizar legado nos próximos 10-15 anos com propósito, não exaustão.",

        "perfil_cpp": "ÁGUIA por estrutura · URUBU por amplificação digital",
        "score_compra": 82,
        "perfil_evidencias": [
            "30 anos de carreira · CNPJ próprio · clínica + 2 hospitais",
            "Único cirurgião de mão titulado da macrorregião",
            "Triplo titular (SBOT + SBCM + SBMH)",
            "Duplo MBA FGV — desejo de gestão visível",
            "5,3k seguidores em 592 posts = 9 seguidores/post (ROI de conteúdo péssimo)",
            "Pagou R$1k sinal = consciência da dor",
        ],
        "dores_top3": [
            ("Cansaço sem retorno proporcional", "30 anos, MBA, e ainda em cidade-base MG dependente de hospital. Por que ainda divide sala?"),
            ("Convênio com ticket baixo", "Atende via HNSF/HRA, volume + convênio, ticket médio comprimido pra subespecialista de mão (que deveria cobrar 3-5x)."),
            ("Sem marca / sem narrativa", "IG sem rosto, sem story, sem ângulo. Vende a 'mão' e não o 'Dr. Eduardo'. Anônimo entre os outros 20 ortopedistas listados em Patos."),
        ],
        "gaps": [
            ("Posicionamento", "É o ÚNICO especialista titulado em cirurgia da mão de Patos pelo Pardini — e não comunica isso. Mata da idade."),
            ("Oferta premium", "Sem produto/programa, só consulta avulsa. Sem escada de valor."),
            ("Funil", "5,3k seguidores ociosos. Sem captura, sem nutrição, sem agendamento via DM/site."),
        ],
        "hooks_abertura": [
            "Eduardo, abri seu perfil agora. 27 anos de carreira, residência com Pardini, dois MBAs FGV. E a sua bio do Instagram diz 'Ortopedista e Traumatologista'. Por que você se apresenta como qualquer um?",
            "Você é provavelmente o único cirurgião de mão titulado da macrorregião de Patos. Quanto disso o paciente sabe antes de pisar no consultório?",
            "Cara, 592 posts e 5,3 mil seguidores. Conta pra mim: o que você sente quando abre o Instagram dos seus colegas de SP?",
        ],
        "objecoes_esperadas": [
            "'Tenho 30 anos de carreira, já vi várias novidades de marketing'",
            "'Patos de Minas não paga ticket de capital'",
            "'Mentoria pra quê? Já sou referência'",
        ],
        "abordagem_recomendada": "Tom respeitoso (sênior). Provocação de LEGADO. NÃO tom de 'aprenda do zero'. Patrick: 'voce construiu uma das clínicas mais sólidas do interior de MG — mas o que isso vai virar nos próximos 10 anos? Quem vai herdar? Ou quem vai chegar e tomar?' Pitch de patamar, não de captação. Closer mais experiente do time.",
        "alerta_homonimo": "82% confiança. Sobrenome combinado raro (japonês+português). Existe um Eduardo Alexandre Castanheira Silva (clínico geral Uberaba) que NÃO é o mesmo. Confirmação tripla: especialidade (mão) + cidade (Patos) + CNPJ + IG. Cuidado com Candidato B (Eduardo Seiji Watanabe, gineco SP) — improvável (sem IG/site).",
        "fontes": [
            "https://eduardoortopedia.com.br/",
            "https://www.instagram.com/dr.eduardowatanabe/",
            "https://www.hnsf.com.br/corpoclinico/view/65",
            "https://www.catalogo.med.br/doutor/eduardo-watanabe-castanheira-1870802.htm",
            "https://consultas.plus/lista-de-empresas/minas-gerais/patos-de-minas/30590217000160-eduardo-watanabe-castanheira-eireli/",
        ],
    },
    {
        "slug": "felipe-ojeda",
        "ordem": 8,
        "hora": "18:00",
        "zoom": "https://us06web.zoom.us/j/82907761728",
        "nome": "Dr. Felipe de Bulhões Ojeda",
        "nome_lista": "Dr Felipe Ojeda",
        "correcao_grafia": "CORREÇÃO MASSIVA via print do Instagram: Felipe NÃO é só Cirurgião Geral. É UROLOGISTA fellow IDOR-SP (RQE 146538). A residência em Cirurgia Geral pelo FMABC é a base; a especialidade ATUAL é Urologia, com posicionamento em 'Saúde do Homem | Tech | Performance'. Currículo MUITO mais elaborado do que dossiê inicial supôs.",
        "especialidade": "Urologia",
        "subespecialidade": "Saúde do Homem · Performance · Tech",
        "cidade": "São Paulo",
        "estado": "SP",
        "crm": "CRM 202291 (UFF) · RQE 146538 (Urologia IDOR-SP) · RQE 114019 (Cirurgia FMABC/TCBC)",
        "formacao": [
            "Medicina UFF — Universidade Federal Fluminense (CRM 202291)",
            "Residência Cirurgia Geral — FMABC (TCBC · RQE 114019)",
            "Residência Urologia — IDOR-SP (RQE 146538) — instituto de referência nacional em urologia",
            "Programa Principles and Practice of Clinical Research — Harvard School of Public Health (PPCR)",
        ],
        "estruturas": [
            "Site próprio: felipebulhoes.com (+3 outros links)",
            "Atuação na Rede D'Or (Hospital São Luiz Itaim · Hospital e Maternidade Brasil)",
            "Hospital Municipal Integrado de Santo Amaro · Hora Certa Campo Limpo (vínculos antigos · checar atualidade)",
        ],
        "credenciais": [
            "Selo azul de verificação no Instagram (autoridade reconhecida)",
            "TCBC — Membro do Colégio Brasileiro de Cirurgiões",
            "Fellow IDOR-SP em Urologia (instituto top 3 nacional em uro)",
            "Programa Harvard PPCR em pesquisa clínica",
            "Posicionamento de marca tech-forward (felipebulhoes.com + Threads + linktree)",
        ],
        "instagram": "@drfelipebulhoes ✓ (verificado azul)",
        "instagram_url": "https://www.instagram.com/drfelipebulhoes/",
        "instagram_aberto": True,
        "instagram_seguidores": "1.017",
        "instagram_posts": "142",
        "instagram_bio": '"Felipe De Bulhões Ojeda · Urologista" — bio expandida: "Urologia IDOR-SP RQE 146538 | Cirurgia FMABC/TCBC RQE 114019 | Médico UFF CRM 202291 | Tech, Performance, Saúde do Homem"',
        "instagram_tom": "Tech-forward, premium-jovem, foco em 'Saúde do Homem'. Foto profissional, terno, semblante sério. Posicionamento de Águia em construção — não de Pato. Threads ativa. Site próprio + 3 outros links externos.",
        "site": "https://felipebulhoes.com/",
        "doctoralia": None,
        "linkedin": None,
        "tagline_atual": '"Tech, Performance, Saúde do Homem"',

        "posicionamento_atual_publico": "Urologista jovem fellow IDOR-SP com narrativa tech-forward em torno de Saúde do Homem, Performance e Tecnologia — currículo de elite (UFF + FMABC/TCBC + IDOR + Harvard PPCR), perfil verificado, site próprio, marca em construção deliberada.",
        "potencial_publico": "Felipe, você fez algo que poucos da sua geração fizeram: <strong>juntou três pilares raros — currículo técnico de elite (UFF + FMABC/TCBC + IDOR + Harvard PPCR), posicionamento de marca tech (Saúde do Homem) e disciplina de presença digital (selo azul, site próprio, Threads).</strong> A pergunta não é 'como começar'. É: como esse alicerce vira um produto premium escalável que cobra pelo nome — não pela hora?",

        "perfil_cpp": "ÁGUIA EM CONSTRUÇÃO (corrigido — não é Pato)",
        "score_compra": 75,
        "perfil_evidencias": [
            "Selo azul verificado + 1.017 seguidores + 142 posts — base sólida em construção",
            "Site próprio felipebulhoes.com + 3 outros links externos = arquitetura digital pensada",
            "Posicionamento NICHADO: 'Saúde do Homem · Performance · Tech' — não cirurgião geral genérico",
            "Currículo elite: UFF + FMABC/TCBC + IDOR-SP + Harvard PPCR",
            "DOIS RQEs (Urologia + Cirurgia) = autoridade técnica dupla",
            "Pagou R$1k sinal = consciência clara da próxima fase",
        ],
        "dores_top3": [
            ("Audiência ainda incompatível com a autoridade", "Selo azul + IDOR + UFF + Harvard com 1.017 seguidores e 142 posts. A engrenagem está montada — falta velocidade. Esse delta é a dor visível."),
            ("Sem produto premium estruturado", "Discurso 'Tech · Performance · Saúde do Homem' é ângulo correto, mas falta o método nomeado, o programa, o ticket assimétrico. O paciente premium ainda compra consulta, não jornada."),
            ("Risco de virar 'mais um' no nicho saúde do homem", "Nicho explodiu em SP. Felipe tem credenciais raras (IDOR + Harvard) que se forem comunicadas como 'mais uma bio de urologista' viram commodity premium. Precisa virar categoria."),
        ],
        "gaps": [
            ("Conversão autoridade → audiência", "Selo azul + currículo de elite ainda não viraram tração de seguidores e leads particulares qualificados."),
            ("Produto e jornada", "Sem programa nomeado, sem oferta premium, sem fila. Só consulta avulsa em ambiente onde o paciente premium quer transformação, não procedimento."),
            ("Diferenciação no nicho saturado", "'Saúde do Homem' é categoria explosiva — sem âncora única (qual aresta dele?), corre risco de diluição."),
        ],
        "hooks_abertura": [
            "Felipe, abri seu Instagram. Selo azul. UFF. FMABC. IDOR. Harvard PPCR. E 1 mil seguidores. Pode escolher: a engrenagem está montada errada ou só falta combustível?",
            "Você é o cara que escolheu 'Tech, Performance, Saúde do Homem' como bio. É a aposta certa. Agora me responde: qual é a UMA coisa nesse pilar que você quer ser referência nacional, e em quanto tempo?",
            "Você tem dois RQEs — urologia IDOR e cirurgia TCBC. Em quantos pacientes que pagam particular do seu próprio nome isso se traduziu nos últimos 30 dias?",
        ],
        "objecoes_esperadas": [
            "'Já estou construindo, só preciso de tempo'",
            "'Saúde do Homem está saturado, não dá pra furar com mais um'",
            "'IDOR me dá visibilidade institucional, eu não preciso de marca pessoal'",
            "'Quero focar em pesquisa também — Harvard PPCR é importante pra mim'",
        ],
        "abordagem_recomendada": "Tom de pares (NÃO 'aprenda do zero' — ele é Águia em construção). Patrick: 'Você está no caminho certo, mas no ritmo errado'. Mateus: case prático de urologista que escalou ticket via método nomeado dentro de Saúde do Homem. Provocar a aresta única dele dentro do nicho — Tech? Hormonal? Reprodutiva? Funcional? Sem aresta única vira mais um. CPP = transformar autoridade em produto e ritmo. Pitch deve ser de aceleração, não de fundação.",
        "alerta_homonimo": "100% confiança após print do Instagram. Selo azul + nome literal 'Felipe De Bulhões Ojeda' + CRM 202291 + RQEs específicos = identidade incontestável. RECONHECER NA CALL: dossiê inicial subestimou — ele NÃO é plantonista cansado, é Águia em construção deliberada.",
        "fontes": [
            "https://www.instagram.com/drfelipebulhoes/",
            "https://felipebulhoes.com/",
            "https://www.rededorsaoluiz.com.br/hospital/sao-luiz-itaim",
            "https://www.escavador.com/sobre/2823316/fellype-de-bulhoes-ojeda",
        ],
    },
]

# Inicial pra avatar quando não tem foto
def iniciais(nome):
    parts = [p for p in nome.replace("Dr.","").replace("Dra.","").replace("(Fellype)","").split() if p and len(p)>1]
    if len(parts) >= 2:
        return (parts[0][0] + parts[-1][0]).upper()
    return parts[0][:2].upper() if parts else "??"

# ============================================================================
# OFERTA · 13 elementos do programa Cirurgião Particular Premium
# Valor mensurável: R$ 300.000 · Intangíveis: 5 elementos sem preço de mercado
# ============================================================================
OFERTA = [
    # MENTORIA
    {"cat": "MENTORIA", "icon": "🎯", "nome": "3 Mentorias individuais PREMIUM", "valor": "R$ 100.000", "imensuravel": False, "highlight": True},
    {"cat": "MENTORIA", "icon": "👥", "nome": "Mentorias quinzenais em grupo com Patrick e/ou Mateus", "valor": "R$ 60.000", "imensuravel": False},
    {"cat": "MENTORIA", "icon": "🚀", "nome": "Onboarding PREMIUM com Patrick e/ou Mateus", "valor": "R$ 30.000", "imensuravel": False},
    # MÉTODO
    {"cat": "MÉTODO", "icon": "📚", "nome": "Área de membros com método PREMIUM (7 pilares)", "valor": "R$ 20.000", "imensuravel": False},
    {"cat": "MÉTODO", "icon": "🗺️", "nome": "Plano de ação acompanhado", "valor": "R$ 30.000", "imensuravel": False},
    # PRESENCIAL
    {"cat": "PRESENCIAL", "icon": "🏛️", "nome": "2 Imersões presenciais/ano (6-7/Ago SP + Mar/27)", "valor": "R$ 10.000", "imensuravel": False},
    {"cat": "PRESENCIAL", "icon": "🩺", "nome": "2 Oficinas para a sua equipe médica", "valor": "R$ 40.000", "imensuravel": False},
    # SUPORTE
    {"cat": "SUPORTE", "icon": "💬", "nome": "Suporte PREMIUM individual via WhatsApp", "valor": "R$ 10.000", "imensuravel": False},
    # IMENSURÁVEIS
    {"cat": "MARCA", "icon": "✨", "nome": "Brand Kit cirúrgico personalizado", "valor": "Imensurável", "imensuravel": True},
    {"cat": "COMUNIDADE", "icon": "🤝", "nome": "Grupo com outros cirurgiões mentorados", "valor": "Imensurável", "imensuravel": True},
    {"cat": "COMUNIDADE", "icon": "🔑", "nome": "Grupo direto com Patrick e Mateus", "valor": "Imensurável", "imensuravel": True},
    {"cat": "RITUAL", "icon": "💎", "nome": "Ritual de primeira cirurgia particular R$50k+", "valor": "Imensurável", "imensuravel": True},
    {"cat": "ELITE", "icon": "👑", "nome": "Club PREMIUM 100K", "valor": "Imensurável", "imensuravel": True},
]

OFERTA_VALOR_TOTAL_MENSURAVEL = 300000  # soma R$
OFERTA_TOTAL_ELEMENTOS = len(OFERTA)
OFERTA_INTANGIVEIS = sum(1 for o in OFERTA if o["imensuravel"])
