# Dados curados dos 8 cirurgiões agendados pra diagnóstico CPP em 06/05/2026
# Fonte: cruzamento subagents + base CPP-Desafio-Maio2026/dossie/consolidado.json

CIRURGIOES = [
    {
        "slug": "tatiana-patruni",
        "ordem": 1,
        "hora": "11:00",
        "zoom": "https://us06web.zoom.us/j/87051724132",
        # IDENTIDADE (público + cirúrgico)
        "nome": "Dra. Tatiana Mauad Patruni",
        "nome_lista": "Dra Tatiana Patrubi",
        "correcao_grafia": "Patrick listou como 'Patrubi'. Grafia oficial em CRM-PR, site, hospitais e Doctoralia: PATRUNI (com N).",
        "especialidade": "Otorrinolaringologia",
        "subespecialidade": "Rinoplastia · Cirurgia Plástica da Face · Otologia",
        "cidade": "Curitiba",
        "estado": "PR",
        "crm": "CRM-PR 25960 · RQE Otorrino 1855",
        "formacao": [
            "UFPR — Universidade Federal do Paraná (2008)",
            "Residência Otorrinolaringologia — PUC-PR / Santa Casa + Cajuru (2009-2011)",
            "Especialização em Otologia e Cirurgia de Implante Coclear (2012)",
            "Pós-graduação em Perícias Médicas — IPOG (2014)",
        ],
        "estruturas": [
            "Hospital São Vicente · Hospital Marcelino Champagnat · Novaclínica (SJP)",
            "Consultório próprio — R. Prof. João Argemiro Loyola, 152 · Seminário · Curitiba",
            "Médica auditora da Prefeitura de Curitiba",
            "Preceptora da Residência de Otorrino — HU Evangélico Curitiba",
            "Docente em pós-graduação de medicina estética",
        ],
        "credenciais": [
            "Preceptora de residência médica (HU Evangélico Curitiba)",
            "Trabalhos em congresso: Síndrome de Binder (2010) e Síndrome de Gradenigo (2012)",
            "14 anos de experiência clínica em otorrino + rinoplastia",
            "Tri-língue: Português, Inglês, Espanhol",
        ],
        "instagram": "@dratatianapatruni",
        "instagram_url": "https://www.instagram.com/dratatianapatruni/",
        "instagram_aberto": True,
        "instagram_seguidores": "9.891",
        "instagram_posts": "828",
        "instagram_bio": '"Dra Tatiana Patruni - Rinoplastia"',
        "instagram_tom": "Educativo / didático (pré-pós rinoplastia, calo ósseo, casos), mas sem narrativa pessoal",
        "site": "https://dratatianapatruni.com.br/",
        "doctoralia": "https://www.doctoralia.com.br/tatiana-mauad-patruni/otorrino/curitiba",
        "linkedin": None,
        "tagline_atual": '"Beleza natural sem mudar drasticamente"',

        # POSICIONAMENTO PÚBLICO (apresentável)
        "posicionamento_atual_publico": "Otorrino que faz rinoplastia natural com viés funcional+estético. Filosofia 'beleza natural sem mudar drasticamente'.",
        "potencial_publico": "Tatiana, sua trajetória conta uma história de profundidade técnica — UFPR, PUC, Otologia, Implante Coclear, Rinoplastia, preceptoria, docência. O próximo capítulo não é sobre acumular mais especialidades. É sobre <strong>concentrar o que você já é</strong> em uma marca que o paciente premium reconheça em 3 segundos.",

        # CIRÚRGICO (oculto)
        "perfil_cpp": "GAVIÃO com traços de PATO",
        "score_compra": None,  # não estava na base do desafio (entrou direto pelo R$1k)
        "perfil_evidencias": [
            "Investiu em marca pessoal (site, IG dedicado @dratatianapatruni com handle 'rinoplastia')",
            "Pagou R$1.000 de sinal — sinal de ambição ativa",
            "MAS 14 anos de carreira e ainda 9k seguidores · 0 reviews Doctoralia",
            "Aceita Unimed/Bradesco/Sanepar — não rompeu para particular puro",
            "Estrutura espalhada: consultório + 3 hospitais + auditoria municipal + preceptoria + docência",
        ],
        "dores_top3": [
            ("Estagnação financeira + ticket comprimido", "Aceita 3 convênios grandes — sinal de volume com ticket pressionado, apesar do CV de elite."),
            ("Cansaço de produzir conteúdo sem retorno proporcional", "828 posts e 9,9k seguidores em nicho que viraliza com antes-e-depois → ROI de produção baixo, frustração latente."),
            ("Sensação de estar abaixo do que merece", "14 anos, preceptora, formação UFPR + PUC + IPOG — currículo de Águia comunicado como Pato. Síndrome do impostor comercial mascarada de 'humildade'."),
        ],
        "gaps": [
            ("Posicionamento", "'Rinoplastia natural' é commodity em IG. Falta promessa quantificável + inimigo declarado + ICP nominal."),
            ("Comercial", "Zero avaliações no Doctoralia depois de 14 anos é colapso de prova social digital. Nem coleta review."),
            ("Monetização", "Estrutura espalhada (consultório + 3 hospitais + auditoria + docência) = clássico 'operário do bisturi' rodando muito pra ganhar mediano. Auditoria municipal é âncora típica de quem segura emprego CLT por medo do particular."),
        ],
        "hooks_abertura": [
            "Tatiana, antes de começar — 14 anos de carreira, formação UFPR e PUC, preceptora de residência, faz rinoplastia. E tem 9 mil seguidores e zero avaliação no Doctoralia. Não é falta de competência. É falta de quê, na sua leitura?",
            "A gente leu seu site. 'Beleza natural sem mudar drasticamente' é o que 800 outros otorrinos com rinoplastia falam. Se a gente pegasse seu Instagram e tirasse o nome, dava pra adivinhar que é você?",
            "Auditora da Prefeitura, preceptora, atende São Vicente, Marcelino, Novaclínica, tem consultório próprio E faz rinoplastia. Quando alguém te pergunta 'o que você faz?', qual é a resposta que sai primeiro?",
        ],
        "objecoes_esperadas": [
            "'Já tenho minha estrutura montada'",
            "'Marketing agressivo não combina com otorrino sério'",
            "'Curitiba é um mercado conservador, paciente busca técnica não show'",
        ],
        "abordagem_recomendada": "Tom firme + espelho duro. Ela é Gavião com casca de Pato — sabe que precisa, mas tem casca de medicina séria. Patrick: pinçar a contradição entre estrutura e resultado. Mateus: trazer caso de outra otorrino-rinoplastista que reposicionou e dobrou ticket.",
        "alerta_homonimo": "97% confiança. CUIDADO: irmã Isabella Mauad Patruni também é médica em Curitiba (cirurgiã geral). Tatiana = otorrino. Não confundir.",
        "fontes": [
            "https://dratatianapatruni.com.br/",
            "https://www.doctoralia.com.br/tatiana-mauad-patruni/otorrino/curitiba",
            "https://saovicentecuritiba.com.br/profissionais/tatiana-mauad-patruni/",
            "https://www.escavador.com/sobre/10851668/tatiana-mauad-patruni",
            "https://www.instagram.com/dratatianapatruni/",
        ],
    },
    {
        "slug": "rafael-bozzo-tacino",
        "ordem": 2,
        "hora": "12:00",
        "zoom": "https://us06web.zoom.us/j/83011506773",
        "nome": "Dr. Rafael Bozzo Tacino",
        "nome_lista": "Dr Rafael Bozzo",
        "correcao_grafia": None,
        "especialidade": "Urologia",
        "subespecialidade": "Uro-Oncologia · Cirurgia Robótica (Da Vinci) · Endourologia · Laparoscopia · Litíase",
        "cidade": "Ribeirão Preto",
        "estado": "SP",
        "crm": "CRM-SP 108598 · RQE 35241",
        "formacao": [
            "FMRP-USP — graduação e residência em Urologia",
            "Mestrado FMRP-USP (2015) — finasterida e PSA em jovens",
            "Fellowship Memorial Sloan-Kettering Cancer Center (NY) — Uro-Oncologia + Cirurgia Robótica",
            "Certificação Intuitive Surgical (Da Vinci)",
        ],
        "estruturas": [
            "Médico Assistente HC FMRP-USP — chefe do setor de Urologia Oncológica",
            "Tacino Urologia — Av. Antônio Diederichsen, 400 · Metropolitan Business Center · Jardim América",
            "Hospital São Lucas Ribeirão Preto",
        ],
        "credenciais": [
            "Membro Titular SBU (TiSBU)",
            "Membro Endourological Society",
            "Banca de mestrado FMRP",
            "Cirurgião Robótico certificado Da Vinci",
            "Fellowship internacional em Sloan-Kettering",
        ],
        "instagram": "@dr.rafael.tacino.uro",
        "instagram_url": "https://www.instagram.com/dr.rafael.tacino.uro/",
        "instagram_aberto": True,
        "instagram_seguidores": "~9.500",
        "instagram_posts": "ativo desde 2023",
        "instagram_bio": '"Dr Rafael Tacino - Urologia"',
        "instagram_tom": "Educacional clínico — urologia, saúde sexual masculina, prevenção. Tom professoral, sem rosto-protagonista, sem CTA, sem oferta",
        "site": "https://www.tacinourologia.com.br/",
        "doctoralia": "https://www.doctoralia.com.br/rafael-bozzo-tacino/urologista/ribeirao-preto",
        "linkedin": None,
        "tagline_atual": '"Cirurgia de Excelência"',

        "posicionamento_atual_publico": "Urologista oncológico de elite acadêmica (USP + Sloan-Kettering) que oferece cirurgia robótica de excelência — comunicado em tom institucional de hospital universitário.",
        "potencial_publico": "Rafael, você carrega no currículo aquilo que mentoria nenhuma constrói: <strong>USP + Sloan-Kettering + Da Vinci + 100% particular</strong>. O ponto de virada não é o que você sabe — é arquitetar uma marca que cobre proporcional ao que você já é. Sair de operador da própria agenda para arquiteto de um sistema que escala.",

        "perfil_cpp": "ÁGUIA",
        "score_compra": 84,
        "perfil_evidencias": [
            "100% particular declarado · consulta R$400 (Doctoralia)",
            "13 reviews 5 estrelas",
            "FMRP-USP + Memorial Sloan-Kettering — top 1% Brasil",
            "Chefe de setor HC-USP-RP",
            "Site profissional + IG ativo + endereço Metropolitan Business Center",
        ],
        "dores_top3": [
            ("Estagnação + ticket abaixo do repertório técnico", "Sloan-Kettering no currículo, R$400 a consulta em RP. Os dois números não conversam."),
            ("Dependência de hospital + indicação acadêmica", "Toda tração vem do HC e do encaminhamento USP — sem entrada autônoma de paciente particular pago. IG dormente, site institucional."),
            ("Síndrome do impostor comercial", "Perfil USP/Sloan tende a separar 'medicina séria' de 'vendas'. Vende excelência genérica, não o nicho craveado (câncer de próstata robótico)."),
        ],
        "gaps": [
            ("Marca pessoal", "Nenhum sistema de conteúdo, nenhuma promessa, nenhuma diferenciação além do diploma. Vende 'cirurgia de excelência' (genérico) quando poderia ser 'o uro-oncologista de Ribeirão treinado em Sloan-Kettering'."),
            ("Comercial", "Sem processo, sem script, sem qualificação, sem ancoragem de preço, sem fechamento. Tabela cirúrgica provavelmente reativa."),
            ("Escala", "Posicionamento ainda 100% individual. Sem produto, sem programa, sem fila de espera. Receita travada nas próprias horas."),
        ],
        "hooks_abertura": [
            "Rafael, você é o cara que pegou Sloan-Kettering e voltou pra Ribeirão. Em quantos pacientes particulares por mês isso está se traduzindo hoje — e quanto você acha que deveria estar?",
            "R$400 a consulta. Sloan-Kettering no currículo. Olha pra esses dois números e me diz se eles conversam.",
            "Abri seu Instagram. 9,5 mil seguidores, último post em dezembro. Você está deixando dinheiro e autoridade na mesa por escolha ou por travamento?",
        ],
        "objecoes_esperadas": [
            "'Já sou particular, já sou referência'",
            "'R$38-42k pra que se já tenho o que CPP promete?'",
            "'Marketing não combina com perfil acadêmico-cirúrgico'",
        ],
        "abordagem_recomendada": "Tom peer-to-peer (NUNCA 'aprenda do zero'). Patrick: 'Você venceu a fase 1. Está na fase 2: virar marca'. CUIDADO: não tratar como Pato/Urubu — ele se ofende. Lead de mais alto valor potencial do dia. Considerar entrada como case ou versão premium da mentoria.",
        "alerta_homonimo": "95% confiança. Sobrenome 'Bozzo Tacino' é raro. Único urologista no Brasil com esse nome.",
        "fontes": [
            "https://www.tacinourologia.com.br/",
            "https://tacino.site.med.br/",
            "https://www.doctoralia.com.br/rafael-bozzo-tacino/urologista/ribeirao-preto",
            "https://www.instagram.com/dr.rafael.tacino.uro/",
            "https://teses.usp.br/teses/disponiveis/17/17137/tde-02022016-093721/publico/RafaelBozzoTacinoOrig.pdf",
        ],
    },
    {
        "slug": "paulo-victor-pereira",
        "ordem": 3,
        "hora": "13:00",
        "zoom": "https://us06web.zoom.us/j/88042216514",
        "nome": "Dr. Paulo Victor Pereira",
        "nome_lista": "Dr Paulo Victor Pereira",
        "correcao_grafia": None,
        "especialidade": "[A CONFIRMAR NA CALL]",
        "subespecialidade": None,
        "cidade": "[A CONFIRMAR]",
        "estado": "?",
        "crm": "[A CONFIRMAR]",
        "formacao": [],
        "estruturas": [],
        "credenciais": [],
        "instagram": None,
        "instagram_url": None,
        "instagram_aberto": False,
        "instagram_seguidores": None,
        "instagram_posts": None,
        "instagram_bio": None,
        "instagram_tom": None,
        "site": None,
        "doctoralia": None,
        "linkedin": None,
        "tagline_atual": None,

        "posicionamento_atual_publico": "Identidade em construção pública. O fato de não indexar em buscas é, em si, um diagnóstico — e uma oportunidade.",
        "potencial_publico": "Paulo Victor, esse encontro vai começar diferente: vamos te conhecer. A boa notícia é que <strong>a tela em branco é uma vantagem</strong> — você não tem narrativa antiga pra desfazer. Vai construir a primeira versão certa.",

        "perfil_cpp": "PROVÁVEL PATO (a confirmar)",
        "score_compra": None,
        "perfil_evidencias": [
            "ALERTA: nome muito comum, NÃO indexa como cirurgião proeminente",
            "Não está na base de 78 pagantes do desafio R$97 — entrou direto pelo R$1k",
            "Identidade hoje: nenhum @ pessoal, nenhum site, nenhum LinkedIn como cirurgião",
            "Pagou R$1.000 sinal = está buscando saída",
        ],
        "dores_top3": [
            ("Sem marca / sem posicionamento", "Nome não indexa, nenhum @ pessoal achado. Identidade digital zerada."),
            ("Convênio + dependência hospital (provável)", "Cirurgiões que vão pra desafio CPP por R$1k quase sempre vêm de pipeline 80%+ convênio."),
            ("Impostor comercial / medo de cobrar particular", "Ausência total de comunicação pública sobre valor, autoridade ou método próprio."),
        ],
        "gaps": [
            ("Identidade digital", "Zerada. Criar @ próprio + bio com promessa clara antes de qualquer outra coisa."),
            ("Encantamento de produto", "Não há nome de procedimento próprio nem método nomeado."),
            ("Processo comercial", "Provavelmente atende quem aparece, sem qualificação prévia."),
        ],
        "hooks_abertura": [
            "Paulo Victor, antes da gente entrar — me confirma seu CRM, cidade e especialidade exata. Tô com 3 candidatos no Brasil com seu nome e quero falar com o cirurgião certo.",
            "Você procurou seu próprio nome no Google ultimamente? Porque eu procurei. E é exatamente esse o problema que a gente vai resolver.",
            "Quanto do seu faturamento hoje vem de convênio, e quanto vem de paciente que te procurou pelo seu nome? Essa razão é o seu termômetro de marca.",
        ],
        "objecoes_esperadas": [
            "'Eu prefiro discrição, marketing não combina comigo'",
            "'Tenho pouco tempo pra produzir conteúdo'",
            "'Cirurgião sério não precisa aparecer'",
        ],
        "abordagem_recomendada": "PRIMEIROS 5 MINUTOS = 100% qualificação de identidade (CRM, cidade, especialidade, ticket atual). NÃO entrar em pitch sem confirmar quem é. Stephanie pode puxar cadastro do desafio antes (CRM/UF declarado no checkout R$1k).",
        "alerta_homonimo": "CRÍTICO. <30% confiança. Múltiplos candidatos: Paulo Victor Paz (Ortop. Caxambu/MG), Paulo Victor Bezerra (Vasc. Francisco Beltrão/PR), Paulo Victor (Neurocir. Fortaleza/CE), Paulo Victor Fernandes Sales (Oftal. CE), Paulo Victor Yamin Pereira (única match exata, profissão não confirmada). Hipótese mais provável: 'Pereira' é sobrenome materno pouco indexado, OU presença digital baixíssima (já é diagnóstico).",
        "fontes": [
            "https://drpaulovictorortopedia.com.br/ (candidato Caxambu)",
            "https://www.doctoralia.com.br/paulo-victor-bezerra/cirurgiao-vascular/francisco-beltrao",
            "https://www.escavador.com/sobre/460308255/paulo-victor-yamin-pereira",
            "https://portal.cfm.org.br/busca-medicos",
        ],
    },
    {
        "slug": "tarik-soares-suleiman",
        "ordem": 4,
        "hora": "14:00",
        "zoom": "https://us06web.zoom.us/j/89649935942",
        "nome": "Dr. Tarik Soares Suleiman",
        "nome_lista": "Dr Tarick Soares",
        "correcao_grafia": "Patrick listou como 'Tarick' (com C). Grafia oficial em CRM, site, Escavador e Receita: TARIK (sem C).",
        "especialidade": "Cirurgia do Aparelho Digestivo",
        "subespecialidade": "Cirurgia Bariátrica e Metabólica · Vesícula · Hérnias · Refluxo (Videolaparoscopia Avançada)",
        "cidade": "Araguaína",
        "estado": "TO",
        "crm": "CRM-TO 4068 · RQE 2506",
        "formacao": [
            "Medicina ITPAC Araguaína (2012)",
            "Residência Cirurgia Geral — Hospital Dr. Carlos Macieira / SES-MA (2014)",
            "Residência Cirurgia do Aparelho Digestivo — HU Presidente Dutra / UFMA (2018)",
            "Fellowship Videolaparoscopia Avançada — Hospital Adventista Silvestre · RJ (2019)",
        ],
        "estruturas": [
            "Hospital São Lucas — Rua 13 de Maio, 840 · Centro · Araguaína",
            "Hospital Regional de Araguaína (HRA) — opera bariátrica",
            "Unimed Araguaína — corpo clínico credenciado",
            "Sócio do ICOD — Instituto de Cirurgia de Obesidade e Diabetes (CNPJ 37.320.580/0001-04)",
        ],
        "credenciais": [
            "Dupla residência (Cirurgia Geral + Aparelho Digestivo) + Fellowship Videolaparoscopia",
            "Publicação no ABCD - Arquivos Brasileiros de Cirurgia Digestiva (2019)",
            "Sócio-fundador de instituto especializado (ICOD)",
            "Cirurgião referência regional norte do Tocantins",
        ],
        "instagram": "@drtariksuleiman",
        "instagram_url": "https://www.instagram.com/drtariksuleiman/",
        "instagram_aberto": True,
        "instagram_seguidores": "—",
        "instagram_posts": "ativo",
        "instagram_bio": '"Dr Tarik · Cirurgião Digestivo · Vesícula e Hérnia · CRM-TO 4068 RQE 2506 · Araguaína-TO"',
        "instagram_tom": "Educativo técnico-prático sobre vesícula, hérnia, refluxo, bariátrica. Linguagem para paciente leigo.",
        "site": "https://drtariksuleiman.com/",
        "doctoralia": None,
        "linkedin": "https://www.linkedin.com/in/tarik-soares-suleiman-588a4a111/",
        "tagline_atual": '"Cirurgião do Aparelho Digestivo especializado em vesícula biliar, hérnias e refluxo"',

        "posicionamento_atual_publico": "Cirurgião digestivo de nicho regional claro em Araguaína — videolaparoscopia avançada num mercado com baixa oferta. Sobrenome único (Suleiman) é ativo de memória local.",
        "potencial_publico": "Tarik, você fez o trabalho duro: ITPAC, UFMA, fellowship no Adventista Silvestre RJ, instituto próprio (ICOD), site, marca digital e atendimento no Hospital São Lucas. <strong>A estrutura está pronta.</strong> O próximo movimento é parar de competir por procedimento e começar a cobrar pelo nome. Bariátrica deixa de ser cirurgia e vira programa premium.",

        "perfil_cpp": "GAVIÃO em ascensão (com tração de Águia)",
        "score_compra": 78,
        "perfil_evidencias": [
            "Site próprio com domínio drtariksuleiman.com",
            "Sócio do ICOD — instituto especializado",
            "RQE 2506 + Fellowship Videolaparoscopia avançada",
            "Instagram profissional bem estruturado",
            "Já se mexeu — não é Pato nem Urubu",
            "Pagou R$1k sinal = capital + busca ativa por escala",
        ],
        "dores_top3": [
            ("Convênio + ticket comprimido", "Unimed Araguaína e HRA dominam volume bariátrico. Tabela Unimed para bariátrica no interior é baixa, e HRA é SUS/regulação."),
            ("Sem marca pessoal forte / posicionamento técnico = invisível no particular", "Site é cartão de visitas com lista de procedimentos, sem narrativa, sem promessa, sem ICP claro. Sem amplificação digital nacional."),
            ("Mercado pequeno + concorrência viral de capital", "Bariátrica em Araguaína concorre com cirurgiões de Palmas, Goiânia, Brasília que aparecem mais. Cirurgião do interior com bom CV + nenhum tráfego digital = teto de fila baixo."),
        ],
        "gaps": [
            ("Oferta", "Vende 'vesícula, hérnia e refluxo' (procedimento) em vez de resultado/transformação para um ICP específico. Não há ticket premium estruturado."),
            ("Máquina", "Zero indício de funil de captação particular — sem lead magnet, sem fluxo de pré-consulta. Volume vem do convênio e do hospital."),
            ("Identidade comercial", "Sócio de 4 num instituto, divide marca com ICOD em vez de construir 'Dr. Tarik Suleiman' como ativo individual."),
        ],
        "hooks_abertura": [
            "Tarik, você tem CV de cirurgião de capital trabalhando em Araguaína. Por que sua agenda particular não reflete isso?",
            "Você abriu o ICOD em 2020 com 3 sócios. Em 5 anos, quanto da sua receita hoje vem do particular fora do convênio?",
            "Quando alguém em Tocantins precisa do melhor cirurgião pra vesícula complicada, eles pensam em você ou no hospital?",
        ],
        "objecoes_esperadas": [
            "'Tocantins não paga ticket de capital'",
            "'Já faço bariátrica no São Lucas, agenda boa'",
            "'Mentoria de SP/Sul não serve pro interior do Norte'",
        ],
        "abordagem_recomendada": "Tom técnico + ambicioso. Dor: 'você construiu tudo certo — só que ainda está cobrando preço de Tocantins'. Mostrar como bariátrico do interior cobra R$45-60k particular puro vendendo PROCESSO (consultoria + cirurgia + acompanhamento), não procedimento. Bariátrica como produto premium, não como cirurgia.",
        "alerta_homonimo": "80% confiança. Sobrenome único (origem árabe). Confirmação tripla: nome+CRM-TO 4068+especialidade digestivo+cidade Araguaína. Verificar autonomia comercial dele dentro do ICOD (4 sócios podem travar marca pessoal).",
        "fontes": [
            "https://drtariksuleiman.com/",
            "https://www.linkedin.com/in/tarik-soares-suleiman-588a4a111/",
            "https://www.instagram.com/drtariksuleiman/",
            "https://www.escavador.com/sobre/9766774/tarik-soares-suleiman",
            "ABCD - Arquivos Brasileiros de Cirurgia Digestiva (2019)",
        ],
    },
    {
        "slug": "julio-fran",
        "ordem": 5,
        "hora": "15:00",
        "zoom": "https://us06web.zoom.us/j/84726454172",
        "nome": "Dr. Júlio Fran da Silva Pinto",
        "nome_lista": "Dr Júlio Fran",
        "correcao_grafia": "Nome completo descoberto na base: Júlio Fran da Silva Pinto. 'Fran' é nome civil, não abreviação.",
        "especialidade": "Ortopedia e Traumatologia",
        "subespecialidade": "Ortopedia Pediátrica",
        "cidade": "Timbó",
        "estado": "SC",
        "crm": "CRM-SC 24030",
        "formacao": [
            "Especialista em Ortopedia e Traumatologia (TEOT)",
            "Subespecialização em Ortopedia Pediátrica",
        ],
        "estruturas": [
            "Consultório próprio — Rua Bolívia, 148 sala 206 · bairro Imigrantes · Timbó-SC",
            "Hospital e Maternidade Oase — Timbó-SC",
            "Atende Unimed",
        ],
        "credenciais": [
            "TEOT — Sociedade Brasileira de Ortopedia e Traumatologia",
            "Subespecialização em Ortopedia Pediátrica (nicho raro no Vale do Itajaí)",
            "Corpo clínico Hospital e Maternidade Oase",
        ],
        "instagram": "@drjuliofran",
        "instagram_url": "https://www.instagram.com/drjuliofran/",
        "instagram_aberto": False,
        "instagram_seguidores": "—",
        "instagram_posts": "—",
        "instagram_bio": "[provavelmente privado ou recém-aberto — não indexa]",
        "instagram_tom": "Inativo / privado",
        "site": None,
        "doctoralia": None,
        "linkedin": None,
        "tagline_atual": None,

        "posicionamento_atual_publico": "Ortopedista pediátrico com consultório próprio em Timbó/SC — um dos poucos do Vale do Itajaí com a subespecialidade. Escassez técnica é o ativo natural; falta sistema digital que comunique.",
        "potencial_publico": "Júlio, você ocupa uma posição rara: <strong>ortopedista pediátrico em uma cidade que dificilmente tem outro</strong>. A escassez já te protegeu por anos — e por isso você não precisou se vender. Mas isso é também o seu teto. O próximo capítulo é virar referência <strong>estadual</strong>, não só municipal.",

        "perfil_cpp": "URUBU com tração latente de Gavião",
        "score_compra": 45,
        "perfil_evidencias": [
            "Consultório próprio + nicho pediátrico + 1 hospital",
            "Sem site, sem Doctoralia, sem Instagram público forte",
            "Atende Unimed (convênio dominante na agenda)",
            "DDD 11 (SP) no celular vs prática SC = origem provável SP, capital pode ser maior do que aparenta",
            "Pagou R$1k de sinal = sinaliza ambição econômica",
        ],
        "dores_top3": [
            ("Cidade pequena + ticket comprimido pelo convênio", "Timbó tem ~46k habitantes. Unimed domina pediatria — ticket pago é baixo, e SUS regula resto."),
            ("Sem qualquer marketing digital", "Invisível no Google sob o nome. Pais que poderiam pagar particular não acham — vão pra ortopedista pediátrico de Joinville/Floripa que aparece."),
            ("Teto regional bloqueado pela falta de sistema de comunicação", "Subespecialidade rara é ativo escondido. Sem narrativa pública, a escassez não vira preço."),
        ],
        "gaps": [
            ("Identidade digital", "Sem site nem perfil indexado. Mãe de classe média alta busca no Instagram antes de marcar — e não acha."),
            ("Posicionamento de nicho", "'Ortopedista pediátrico do Vale do Itajaí' é categoria existente que ele não está ocupando publicamente."),
            ("Funil comercial", "Nenhum ponto de captura (link, WhatsApp Business, formulário). Toda agenda é receptiva via convênio."),
        ],
        "hooks_abertura": [
            "Júlio, antes de tudo — você é o ortopedista PEDIÁTRICO de Timbó, certo? Quero confirmar porque é raríssimo achar um no Vale do Itajaí.",
            "Vi que seu Instagram está fechado. Isso é decisão consciente ou é uma das coisas que você quer destravar com a CPP?",
            "Você pagou sinal antes da call. Isso me diz que tem dinheiro entrando. Me conta: o problema é faturamento, margem ou cansaço — qual desses é o que mais te tira o sono hoje?",
        ],
        "objecoes_esperadas": [
            "'Em Timbó não tem mercado pra particular premium'",
            "'Pais querem convênio, não particular'",
            "'Ortopedia pediátrica é serviço público, mães não pagam R$1500'",
            "'CPP é caro pra realidade do interior'",
        ],
        "abordagem_recomendada": "Tom de convicção + caso real. Mostrar mentorados CPP do interior que viraram particular puro. ROI: 1 cirurgia ortopédica pediátrica particular paga 1/3 do CPP. Falar parcelamento longo. CUIDADO com qualificação financeira — pode ser Pato fingindo Gavião.",
        "alerta_homonimo": "Match único confirmado: CRM-SC 24030, Timbó, ortopedia pediátrica. Sem ambiguidade.",
        "fontes": [
            "https://agendaconvenio.com/unimed/timbo/julio-fran-da-silva-pinto",
            "https://hospitaloase.com.br/profissionais/",
            "https://www.instagram.com/drjuliofran/",
        ],
    },
    {
        "slug": "marina-marangon-melhado",
        "ordem": 6,
        "hora": "16:00",
        "zoom": "https://us06web.zoom.us/j/82606867642",
        "nome": "Dra. Marina Marangon Melhado",
        "nome_lista": "Dra Mariana Marangon",
        "correcao_grafia": "Patrick listou como 'Mariana'. Nome correto em CRM, site, CNN, Correio Braziliense: MARINA.",
        "especialidade": "Ortopedia e Traumatologia",
        "subespecialidade": "Cirurgia do Pé e Tornozelo · Medicina Esportiva · Ortopedia Integrativa (Nutrologia + Hormônios + Regenerativa)",
        "cidade": "São Paulo",
        "estado": "SP",
        "crm": "CRM-SP 179.632 · CRM-MT 7454 · RQE 121.033",
        "formacao": [
            "Medicina UNIC Cuiabá",
            "Residência Ortopedia — Beneficência Portuguesa de Ribeirão Preto",
            "Pós Nutrologia — Uningá + Plenitude",
            "Pós Nutrição Esportiva + Medicina Estética",
            "Certificações em hormonologia + terapias EV/IM",
        ],
        "estruturas": [
            "Clínica AGHA — R. Bento de Andrade, 436 · Jardim Paulista · SP",
            "Sala secundária — R. Joaquim Floriano, 413 · 9º andar · Itaim Bibi",
            "100% PARTICULAR — não aceita convênios",
        ],
        "credenciais": [
            "Colunista CNN Brasil (Saúde)",
            "Colunista Correio Braziliense (Radar)",
            "Fonte recorrente THMais / NovaBrasil",
            "Múltiplas matérias mainstream em 2025 (artrose, fascite, joanete, longevidade)",
        ],
        "instagram": "@dramarinamelhado",
        "instagram_url": "https://www.instagram.com/dramarinamelhado/",
        "instagram_aberto": True,
        "instagram_seguidores": "moderado-alto",
        "instagram_posts": "alta frequência",
        "instagram_bio": '"Ortopedia e Traumatologia - Regenerativa, São Paulo-SP | CRM-SP 179.632 | RQE 121.033 | Cirurgia do Pé e Tornozelo + Medicina Esportiva + Nutrologia"',
        "instagram_tom": "Educacional sofisticado, premium-acessível. 'Sair da dor é possível'. Linha integrativa-regenerativa.",
        "site": "https://www.dramarinamelhado.com.br/",
        "doctoralia": "https://www.doctoralia.com.br/marina-marangon-melhado/ortopedista-traumatologista/sao-paulo",
        "linkedin": None,
        "tagline_atual": '"Viver com dor não precisa ser o seu normal"',

        "posicionamento_atual_publico": "Ortopedista integrativa que trata dor crônica como sintoma sistêmico — junta cirurgia do pé/tornozelo, hormônios, nutrologia e regenerativa pra devolver performance.",
        "potencial_publico": "Marina, autoridade técnica você já tem. CNN, Correio, Jardim Paulista, particular puro, narrativa diferenciada. <strong>O próximo movimento não é construir — é arquitetar.</strong> Transformar agenda lotada em império com agenda <em>limitada</em> e ticket assimétrico. Virar categoria, não competidora.",

        "perfil_cpp": "ÁGUIA",
        "score_compra": 84,
        "perfil_evidencias": [
            "100% particular puro — zero convênio (sinal mais forte)",
            "Endereço Jardim Paulista + Itaim (territórios elite SP)",
            "Mídia tier-1: CNN, Correio Braziliense",
            "Narrativa diferenciada (longevidade + integrativa)",
            "Mudou MT→SP buscando outro nível — comportamento de Águia em escala",
            "Site próprio + IG ativo + base editorial sólida",
        ],
        "dores_top3": [
            ("Teto invisível / dor de identidade", "Já é referência local SP, mas ainda não nacional. Fome de virar 'a Dra. Ana Hirsch da ortopedia integrativa'. CNN+Correio sem virar autoridade-marca; consulta R$300 — abaixo do que entrega."),
            ("Dependência de fluxo de marketing", "Particular pura sem convênio = se a panela de leads esfria, agenda cai. Sem produto digital, sem fila de espera blindada."),
            ("Concorrência nicho integrativo brutal", "Boom de longevidade em SP atrai todo médico-influencer. Marina ainda é 'uma das' — não 'a'."),
        ],
        "gaps": [
            ("Método proprietário", "Faz ortopedia integrativa, mas não tem nome próprio do protocolo (ex: 'Protocolo Marina' / 'Método XYZ'). Vira commodity premium em vez de categoria."),
            ("Site/funil sub-aproveitado", "Página tem '555-555-5555' e 'meuemail@email.com.br' — placeholder de template não-customizado. Funil quebrado."),
            ("Ticket abaixo do potencial", "R$300 consulta em Jardim Paulista, sendo entrevistada na CNN, é underpricing brutal. Águia que ainda cobra preço de Gavião."),
        ],
        "hooks_abertura": [
            "Marina, vi que você saiu de Cuiabá pra construir nome em SP. Já é referência local, CNN, Correio. Pergunta cirúrgica: o que falta pra você virar referência nacional — sem virar refém da própria agenda?",
            "R$300 a consulta em Jardim Paulista, sendo entrevistada na CNN. O que te impede de cobrar R$1.500 amanhã e dobrar a fila de espera?",
            "Você já é Águia tecnicamente. CPP não é pra te ensinar a sair do convênio. É pra te transformar em categoria, não competidora. Quer que eu mostre como?",
        ],
        "objecoes_esperadas": [
            "'Já sou particular pura, já tenho mídia (CNN), o que CPP me dá?'",
            "'Já faço marketing, R$38k é investimento alto pra ROI marginal'",
            "'Quero entender se vocês atendem nível elite ou é básico'",
        ],
        "abordagem_recomendada": "Tom elite-para-elite. NÃO vender 'sair do convênio' (já saiu). Vender ESCALA E PERPETUAÇÃO: agenda lotada → produto digital, expansão para outras capitais, fila de espera, ticket 5-15k/consulta. Patrick abre com case de Águia que aplicou CPP e dobrou ticket. Tom sem afago, ela testa profundidade.",
        "alerta_homonimo": "90% confiança. Nome composto único. Sem ambiguidade. Risco residual: ser Gavião-com-discurso-de-Águia (verificar quanto fatura/mês na call).",
        "fontes": [
            "https://www.dramarinamelhado.com.br/",
            "https://www.doctoralia.com.br/marina-marangon-melhado/ortopedista-traumatologista/sao-paulo",
            "https://www.cnnbrasil.com.br/saude/joelho-travado-dor-pode-ser-sinal-precoce-de-artrose/",
            "https://www.correiobraziliense.com.br/cbradar/dra-marina-melhado-ortopedista-como-aliviar-a-dor-da-fascite-plantar-de-forma-segura/",
        ],
    },
    {
        "slug": "eduardo-watanabe-castanheira",
        "ordem": 7,
        "hora": "17:00",
        "zoom": "https://us06web.zoom.us/j/82920171401",
        "nome": "Dr. Eduardo Watanabe Castanheira",
        "nome_lista": "Dr Eduardo Watanabe",
        "correcao_grafia": None,
        "especialidade": "Ortopedia e Traumatologia",
        "subespecialidade": "Cirurgia da Mão (microcirurgia reconstrutiva)",
        "cidade": "Patos de Minas",
        "estado": "MG",
        "crm": "CRM-MG 27899",
        "formacao": [
            "Medicina FCMMG (1989-1994)",
            "Residência Ortopedia/Traumatologia — Hospital Ortopédico BH (1995-1997)",
            "Fellowship Cirurgia da Mão (1998) — sob Dr. Arlindo Pardini",
            "MBA Gestão Empresarial — FGV",
            "MBA Gestão de Saúde — FGV",
        ],
        "estruturas": [
            "Consultório próprio — R. Padre Caldeira, 386 · Centro · Patos de Minas",
            "Hospital Nossa Senhora de Fátima (HNSF) — corpo clínico",
            "Hospital Regional Antônio Dias",
            "CNPJ próprio — Eduardo Watanabe Castanheira Eireli (30.590.217/0001-60)",
        ],
        "credenciais": [
            "Membro Titular SBOT",
            "Membro Titular Sociedade Brasileira de Cirurgia da Mão",
            "Membro Titular Sociedade Brasileira de Medicina Hiperbárica",
            "Duplo MBA FGV",
            "30 anos de carreira · referência regional Triângulo Mineiro/Alto Paranaíba",
            "Único cirurgião de mão titulado da macrorregião",
        ],
        "instagram": "@dr.eduardowatanabe",
        "instagram_url": "https://www.instagram.com/dr.eduardowatanabe/",
        "instagram_aberto": True,
        "instagram_seguidores": "5.300",
        "instagram_posts": "592",
        "instagram_bio": '"Ortopedista e Traumatologista"',
        "instagram_tom": "Educativo (túnel do carpo, dedo em gatilho, Dupuytren). Tom institucional, professoral, sem rosto, sem narrativa pessoal.",
        "site": "https://eduardoortopedia.com.br/",
        "doctoralia": "https://www.catalogo.med.br/doutor/eduardo-watanabe-castanheira-1870802.htm",
        "linkedin": None,
        "tagline_atual": '"Estruturas tão complexas quanto as mãos exigem cuidado especializado"',

        "posicionamento_atual_publico": "Especialista técnico em mão de Patos de Minas — credenciais e didática. Vende competência, não desejo. Referência consolidada boca-a-boca em comunidade de ~150k habitantes.",
        "potencial_publico": "Doutor Eduardo, 30 anos de carreira, formação com Arlindo Pardini, titular em 3 sociedades, referência histórica do Alto Paranaíba. <strong>O capítulo agora é outro.</strong> Não é construir do zero — é decidir o que vai deixar quando parar. Como monetizar legado nos próximos 10-15 anos com propósito, não exaustão.",

        "perfil_cpp": "ÁGUIA por estrutura · URUBU por amplificação digital",
        "score_compra": 82,
        "perfil_evidencias": [
            "30 anos de carreira · CNPJ próprio · clínica + 2 hospitais",
            "Único cirurgião de mão titulado da macrorregião",
            "Triplo titular (SBOT + SBCM + SBMH)",
            "Duplo MBA FGV — desejo de gestão visível",
            "5,3k seguidores em 592 posts = 9 seguidores/post (ROI de conteúdo péssimo)",
            "Pagou R$1k sinal = consciência da dor",
        ],
        "dores_top3": [
            ("Cansaço sem retorno proporcional", "30 anos, MBA, e ainda em cidade-base MG dependente de hospital. Por que ainda divide sala?"),
            ("Convênio com ticket baixo", "Atende via HNSF/HRA, volume + convênio, ticket médio comprimido pra subespecialista de mão (que deveria cobrar 3-5x)."),
            ("Sem marca / sem narrativa", "IG sem rosto, sem story, sem ângulo. Vende a 'mão' e não o 'Dr. Eduardo'. Anônimo entre os outros 20 ortopedistas listados em Patos."),
        ],
        "gaps": [
            ("Posicionamento", "É o ÚNICO especialista titulado em cirurgia da mão de Patos pelo Pardini — e não comunica isso. Mata da idade."),
            ("Oferta premium", "Sem produto/programa, só consulta avulsa. Sem escada de valor."),
            ("Funil", "5,3k seguidores ociosos. Sem captura, sem nutrição, sem agendamento via DM/site."),
        ],
        "hooks_abertura": [
            "Eduardo, abri seu perfil agora. 27 anos de carreira, residência com Pardini, dois MBAs FGV. E a sua bio do Instagram diz 'Ortopedista e Traumatologista'. Por que você se apresenta como qualquer um?",
            "Você é provavelmente o único cirurgião de mão titulado da macrorregião de Patos. Quanto disso o paciente sabe antes de pisar no consultório?",
            "Cara, 592 posts e 5,3 mil seguidores. Conta pra mim: o que você sente quando abre o Instagram dos seus colegas de SP?",
        ],
        "objecoes_esperadas": [
            "'Tenho 30 anos de carreira, já vi várias novidades de marketing'",
            "'Patos de Minas não paga ticket de capital'",
            "'Mentoria pra quê? Já sou referência'",
        ],
        "abordagem_recomendada": "Tom respeitoso (sênior). Provocação de LEGADO. NÃO tom de 'aprenda do zero'. Patrick: 'voce construiu uma das clínicas mais sólidas do interior de MG — mas o que isso vai virar nos próximos 10 anos? Quem vai herdar? Ou quem vai chegar e tomar?' Pitch de patamar, não de captação. Closer mais experiente do time.",
        "alerta_homonimo": "82% confiança. Sobrenome combinado raro (japonês+português). Existe um Eduardo Alexandre Castanheira Silva (clínico geral Uberaba) que NÃO é o mesmo. Confirmação tripla: especialidade (mão) + cidade (Patos) + CNPJ + IG. Cuidado com Candidato B (Eduardo Seiji Watanabe, gineco SP) — improvável (sem IG/site).",
        "fontes": [
            "https://eduardoortopedia.com.br/",
            "https://www.instagram.com/dr.eduardowatanabe/",
            "https://www.hnsf.com.br/corpoclinico/view/65",
            "https://www.catalogo.med.br/doutor/eduardo-watanabe-castanheira-1870802.htm",
            "https://consultas.plus/lista-de-empresas/minas-gerais/patos-de-minas/30590217000160-eduardo-watanabe-castanheira-eireli/",
        ],
    },
    {
        "slug": "felipe-ojeda",
        "ordem": 8,
        "hora": "18:00",
        "zoom": "https://us06web.zoom.us/j/82907761728",
        "nome": "Dr. Felipe (Fellype) de Bulhões Ojeda",
        "nome_lista": "Dr Felipe Ojeda",
        "correcao_grafia": "Nome acadêmico assina 'Fellype' (com Y). Variações: Felipe ou Fellype de Bulhões Ojeda.",
        "especialidade": "Cirurgia Geral",
        "subespecialidade": "Emergência cirúrgica · Pesquisa Clínica",
        "cidade": "São Paulo",
        "estado": "SP",
        "crm": "CRM-SP (registrado, número não capturado publicamente)",
        "formacao": [
            "Medicina UFF — Universidade Federal Fluminense (Niterói, 2017)",
            "Residência Cirurgia Geral — FMABC (2021)",
            "Programa Principles and Practice of Clinical Research — Harvard School of Public Health (PPCR)",
            "Monitor de Anatomia Humana e Semiologia Médica na graduação",
        ],
        "estruturas": [
            "Hospital Municipal Integrado de Santo Amaro",
            "Hospital Dia Hora Certa Campo Limpo",
            "Hospital São Luiz Itaim — Rede D'Or",
            "Hospital e Maternidade Brasil — Rede D'Or",
        ],
        "credenciais": [
            "Membro Adjunto do Colégio Brasileiro de Cirurgiões (CBC)",
            "Bolsista MEC durante residência FMABC",
            "Programa Harvard PPCR",
            "Atuação em 2 unidades da Rede D'Or",
            "Coautoria em trabalho sobre anestesia em Síndrome da Pessoa Rígida (UFF)",
        ],
        "instagram": None,
        "instagram_url": None,
        "instagram_aberto": False,
        "instagram_seguidores": None,
        "instagram_posts": None,
        "instagram_bio": "[sem perfil profissional ativo localizável]",
        "instagram_tom": "Ausente",
        "site": None,
        "doctoralia": None,
        "linkedin": None,
        "tagline_atual": None,

        "posicionamento_atual_publico": "Cirurgião jovem de currículo sólido (UFF + FMABC + Harvard PPCR + CBC) que ainda vende horas de plantão e vagas em hospital, sem nome próprio, sem consultório, sem mercado particular constituído.",
        "potencial_publico": "Felipe, você é geração que viu colegas que estudaram menos virarem 'os médicos famosos do Insta' enquanto operava de plantão. <strong>A boa notícia é que você ainda tem a tela em branco.</strong> O caminho é exatamente sobre como sair do plantão e virar referência num nicho — sem virar o que você não respeita.",

        "perfil_cpp": "PATO em transição inicial pra URUBU",
        "score_compra": 48,
        "perfil_evidencias": [
            "Depende 100% de hospital pra ter agenda",
            "Renda fragmentada em 4 instituições",
            "Sem autoridade pública · sem ticket próprio",
            "Modelo 'vende horas/escala'",
            "Entrou na Rede D'Or (2 unidades) — começou a aprender o jogo do privado, mas como PS",
            "Pagou R$1k sinal = busca saída",
        ],
        "dores_top3": [
            ("Estagnação + cansaço sem retorno", "4 vínculos hospitalares = rotina exaustiva, faturamento por hora, teto baixo."),
            ("Dependência institucional + medo de cobrar particular", "Toda receita vem de instituição; nenhum sinal de consultório próprio, site, Doctoralia, IG."),
            ("Sem marca / impostor comercial", "Currículo de elite (UFF+FMABC+CBC+Harvard) NÃO convertido em autoridade pública. Cirurgião geral sem nicho declarado é o perfil mais difícil de vender particular."),
        ],
        "gaps": [
            ("Presença digital absoluta", "Sem Instagram, sem site, sem Doctoralia, sem LinkedIn ativo. Invisível pro paciente particular."),
            ("Nicho/posicionamento", "'Cirurgião geral' genérico em SP é commodity. Precisa eleger procedimento-âncora (hérnia, vesícula, parede abdominal, proctologia, bariátrica?)."),
            ("Processo comercial", "Sem consultório próprio identificado, sem funil, sem ticket, sem secretária, sem fechamento. Está no zero do PREMIUM."),
        ],
        "hooks_abertura": [
            "Felipe, antes de qualquer coisa — me confirma: você é o Fellype de Bulhões Ojeda, cirurgião geral, formado UFF e FMABC, hoje rodando entre Santo Amaro, Campo Limpo, São Luiz Itaim e Hospital Brasil?",
            "Você tem currículo de top 1% — UFF, FMABC, CBC, Harvard PPCR — e zero presença digital. Foi escolha consciente ou nunca sobrou tempo entre os plantões?",
            "Quantas horas por mês você ainda vende pra hospital hoje? E quanto disso é do seu bolso, do seu nome, com paciente que veio te procurar?",
        ],
        "objecoes_esperadas": [
            "'Cirurgia geral em SP é commodity, ninguém paga premium'",
            "'Não tenho público formado'",
            "'Sou plantonista, não tenho tempo'",
            "'Preciso primeiro de subespecialidade'",
        ],
        "abordagem_recomendada": "Tom estratégico de carreira. Mostrar que cirurgião geral PODE virar premium se posicionar nicho específico (hérnia, vesícula laparoscópica eletiva). Patrick fala estratégia, Mateus mostra o caminho prático que ele mesmo trilhou. CUIDADO: ticket pode ser desafio. Pitch deve ser visão de 3-5 anos, não retorno imediato. Verificar capital próprio.",
        "alerta_homonimo": "70% confiança. Match forte por sobrenome único + especialidade. Mas sem CRM confirmado, sem IG público, sem Doctoralia, risco real de ser homônimo. Validar identidade nos primeiros 90s (Hook #1) antes de qualquer diagnóstico.",
        "fontes": [
            "https://www.escavador.com/sobre/2823316/fellype-de-bulhoes-ojeda",
            "https://www.rededorsaoluiz.com.br/hospital/sao-luiz-itaim",
            "https://sanarmed.com/residencia-medica-na-fmabc-faculdade-de-medicina-do-abc/",
            "https://portal.cfm.org.br/busca-medicos",
        ],
    },
]

# Inicial pra avatar quando não tem foto
def iniciais(nome):
    parts = [p for p in nome.replace("Dr.","").replace("Dra.","").replace("(Fellype)","").split() if p and len(p)>1]
    if len(parts) >= 2:
        return (parts[0][0] + parts[-1][0]).upper()
    return parts[0][:2].upper() if parts else "??"
