# FBI Data — Investigação profunda dos 8 cirurgiões + imagens cinematográficas 4K
# Para usar no painel operacional (uso interno) e nas individuais (filtrado para apresentação)

BG_IMAGES = {
    "tatiana-patruni": "imagens/01-tatiana-patruni.png",
    "rafael-bozzo-tacino": "imagens/02-rafael-bozzo-tacino.png",
    "paulo-victor-pereira": "imagens/03-paulo-victor-pereira.png",
    "tarik-soares-suleiman": "imagens/04-tarik-soares-suleiman.png",
    "julio-fran": "imagens/05-julio-fran.png",
    "marina-marangon-melhado": "imagens/06-marina-marangon-melhado.png",
    "eduardo-watanabe-castanheira": "imagens/07-eduardo-watanabe.png",
    "felipe-ojeda": "imagens/08-felipe-ojeda.png",
}

# Para cada cirurgião:
# - quote_manifesto: frase forte de abertura (apresentável)
# - narrativa_publica: parágrafo respeitoso reconhecendo trajetória (apresentável)
# - descobertas_publicas: lista de achados que IMPRESSIONAM mostrando que estudamos (apresentável)
# - pitch_direcionado: 4 etapas de transformação que CPP vai entregar especificamente (apresentável)
# - pontos_internos: ganchos cirúrgicos pra Patrick (interno do painel)

FBI = {
    "tatiana-patruni": {
        "quote_manifesto": "Quem opera ouvido de criança tem mão diferente de quem só faz estética.",
        "narrativa_publica": "Você fez UFPR, PUC, dois anos de Otologia e Implante Coclear no Pequeno Príncipe operando criança surda, e construiu com a Isabella e o Dr. Marcos a PETRA Clinic by Patruni — uma clínica de família dentro de uma família tradicional empresária de Curitiba. Tem 14 anos de carreira, é preceptora de residência no HU Evangélico, atende em quatro hospitais e ainda é auditora médica da Prefeitura. A história aqui não é de quem precisa começar. É de quem precisa <em>concentrar.</em>",
        "descobertas_publicas": [
            "<strong>UFPR (2003-2008) + Residência PUC-PR (2009-2011)</strong> — Santa Casa + Cajuru, formação completa em Curitiba",
            "<strong>Fellowship Pequeno Príncipe (2011-2013)</strong> — dois anos operando implante coclear pediátrico, raro no nicho rinoplástico",
            "<strong>PETRA Clinic by Patruni</strong> — clínica de família com Dra. Isabella Mauad Patruni Sarraff (cunhada/irmã) e Dr. Marcos Cesar Amaral Patruni",
            "<strong>Preceptora HU Evangélico de Curitiba</strong> + Auditora Médica da Prefeitura de Curitiba",
            "<strong>Trilíngue</strong>: Português, Inglês, Espanhol",
            "<strong>Site oficial</strong> com 'Não é apenas sobre mudar seu rosto, é sobre revelar sua verdadeira beleza'",
            "<strong>Bio Instagram</strong>: 'Há 15 anos apaixonada por entregar beleza com naturalidade'",
            "<strong>Hospitais</strong>: São Vicente · Marcelino Champagnat · Novaclínica · Pequeno Príncipe · HU Evangélico (preceptoria)",
        ],
        "pitch_direcionado": [
            ("Eleger uma aresta dentro de Rinoplastia",
             "Entre estética conservadora, funcional, étnica e secundária — escolher UMA narrativa afiada que substitua o 'beleza natural sem mudar drasticamente' que outros 800 otorrinos repetem"),
            ("Empacotar a jornada premium",
             "Mapeamento + simulação + cirurgia + acompanhamento de 12 meses como produto único de R$ 45-65k, em vez de procedimento avulso"),
            ("Coletar prova social digital sistematicamente",
             "Fechar 30 reviews em 30 dias no Doctoralia (zero hoje, depois de 14 anos) e construir banco de antes-e-depois ético e narrativo"),
            ("Reduzir dispersão das 5 frentes",
             "Auditar quais vínculos públicos e hospitalares constroem autoridade vs quais diluem foco. A PETRA Clinic não pode ser plano B — precisa ser plano A.")
        ],
        "pontos_internos": [
            "Família Patruni é empresária tradicional Curitiba (3 empresas: clínica + Patruni Inovações Tecnologia + Executive Tour). Tatiana casou com herdeiro (Dr. Marcos Cesar)",
            "Concorrente direto consolidado: Dr. Cezar Berger (PhD UFPR, Instituto Rinoplastia e Plástica do Paraná). Ela está 1 nível abaixo em autoridade pública",
            "Auditoria municipal = âncora CLT clássica de Pato. Ela ainda não confia 100% no consultório premium",
            "Doctoralia: ZERO reviews em 17 anos = matéria-prima ouro nunca pedida",
            "Ticket atual estimado R$22-30k rinoplastia · espaço claro pra R$35-40k (mercado Curitiba premium vai até R$45k)",
        ],
    },

    "rafael-bozzo-tacino": {
        "quote_manifesto": "Você venceu a fase 1. Está na fase 2: virar marca.",
        "narrativa_publica": "Você se formou na FMRP-USP, fez residência no HC, defendeu mestrado em 2015 com o Prof. Dr. Rodolfo Borges dos Reis — o primeiro urologista brasileiro convidado para o Consenso Mundial de Câncer de Próstata Avançado. A banca foi Cologna e Tucci. Depois disso, você fez fellowship no Memorial Sloan-Kettering em Nova York. Voltou pra Ribeirão e foi parte da equipe que realizou a primeira cirurgia robótica de Ribeirão Preto, em junho de 2019, no São Lucas. Hoje é Médico Assistente e chefe da Urologia Oncológica do HC-FMRP-USP. Tem perfil verificado, 440 posts no Instagram, 7 destaques temáticos organizados, linktree e Threads ativos. <em>Currículo e produção, você tem.</em>",
        "descobertas_publicas": [
            "<strong>FMRP-USP graduação + residência + mestrado (2015)</strong> — tese sobre finasterida e PSA em pacientes jovens, orientada por Rodolfo Borges dos Reis",
            "<strong>Banca de mestrado</strong>: Adauto José Cologna (presidente) + Silvio Tucci Junior — peso máximo USP",
            "<strong>Fellowship Memorial Sloan-Kettering Cancer Center, NY</strong> — Uro-Oncologia + Cirurgia Robótica minimamente invasiva",
            "<strong>Certificação Da Vinci</strong> — Intuitive Surgical (Atlanta/EUA)",
            "<strong>Médico Assistente HC-FMRP-USP</strong> — chefe do setor de Urologia Oncológica",
            "<strong>Primeira cirurgia robótica de Ribeirão Preto</strong> — junho/2019, Hospital São Lucas (parte da equipe inaugural)",
            "<strong>Hospital São Lucas atingiu 1.000 cirurgias robóticas em 2024</strong> — você é parte dessa história",
            "<strong>Membro Titular</strong>: SBU (TiSBU) · Endourological Society · Confederación Americana de Urología (CAU) · American Urological Association (AUA)",
            "<strong>Endereço premium</strong>: Av. Antônio Diederichsen 400, Metropolitan Business Center, Jardim América",
            "<strong>Doctoralia</strong>: 13 reviews · 5 estrelas · palavras recorrentes 'didático', 'humanizado', 'esclarece'",
            "<strong>Instagram verificado</strong> @dr.rafael.tacino.uro · 440 posts · 4.025 seguidores · 7 destaques temáticos (Disf Erétil · Cálculos · Robótica · Vasectomia · Hormonal · Testes · Perguntas) · linktree + Threads ativos",
        ],
        "pitch_direcionado": [
            ("Reposicionar como categoria, não como urologista genérico",
             "'O uro-oncologista de Ribeirão Preto treinado em Sloan-Kettering' precisa estar na bio, no site, na primeira frase de qualquer apresentação. Diferenciação cravada"),
            ("Subir o ticket de consulta de R$400 para R$800-1.200",
             "Paciente que paga R$400 hoje, paga R$1.000 amanhã pra ver o cara do Sloan-Kettering. O preço atual é incoerente com o repertório técnico"),
            ("Construir o 'Programa Próstata Premium' robótico",
             "Jornada robótica completa — pré-cirúrgico + cirurgia robótica + acompanhamento 24 meses — como ticket único de R$ 80-120k, em vez de procedimento isolado"),
            ("Sair de operador individual para arquiteto de sistema",
             "Recrutar urologistas júnior pra escalar volume mantendo o nome como marca-mãe; lançar consultoria/mentoria pra urologistas que querem migrar pra robótica; estruturar Tacino Urologia como marca institucional"),
        ],
        "pontos_internos": [
            "Sócio operacional Dr. Tiago Borelli Bovo (Johns Hopkins, +1.500 cirurgias robóticas, Diretor Robótico São Lucas) é a sombra que ofusca Rafael. Ele é #2 num jogo onde quer ser #1",
            "11 anos sem publicar pós-tese (2015→2026). Pode ter ficado 'em dívida' com o orientador-pai (Reis)",
            "Currículo Champions League, ticket Série C (R$400)",
            "Perfil yahoo.com.br + IG sem rosto-protagonista = conservador digitalmente. Patrick precisa ser preciso, não histriônico",
            "Lead AAA potencial · score 84 · considerar entrada como case ou versão premium",
        ],
    },

    "paulo-victor-pereira": {
        "quote_manifesto": "151 reviews 5 estrelas é matéria-prima de ouro. Falta posicionamento.",
        "narrativa_publica": "Você é sócio fundador da ICOD desde 2018 — oito anos consolidando uma das clínicas multidisciplinares ortopédicas mais respeitadas de Brasília, com presença em Águas Claras e Paranoá. É o único cirurgião de pé e tornozelo dos dez sócios. Tem 151 avaliações verificadas no Doctoralia, todas cinco estrelas. Os pacientes usam as mesmas três palavras pra te descrever: <em>atencioso, claro, tranquilo.</em>",
        "descobertas_publicas": [
            "<strong>CRM-DF 22186 · RQE 17862</strong> — Ortopedia e Traumatologia, subespecialização Pé e Tornozelo",
            "<strong>Sócio fundador ICOD desde 01/06/2018</strong> — Instituto da Coluna Vertebral, Ortopedia, Dor e Otorrino (CNPJ 30.599.744/0001-35)",
            "<strong>Único cirurgião de pé e tornozelo dos 10 sócios</strong> da ICOD — sem concorrência interna no nicho",
            "<strong>2 endereços</strong>: Águas Claras (Albany Medical Center, R. 05 Norte Lt 03 Loja 06) + Paranoá (Área Especial Qd 02 Cj K)",
            "<strong>151 avaliações verificadas Doctoralia · 5,0 estrelas</strong>",
            "<strong>Padrões nas reviews</strong>: 'atencioso, pontual, simpático, claro, tranquilo, esclarece todas as dúvidas, não tira a esperança'",
            "<strong>Carteira robusta de convênios institucionais</strong>: Postal Saúde · Saúde Caixa · BACEN · STF-MED · TST/TRE Saúde · Casembrapa · Conab · Serpro",
            "<strong>Albany Medical Center</strong> — hub premium em Águas Claras junto a metrô Arniqueiras",
        ],
        "pitch_direcionado": [
            ("Eleger sub-nicho dentro de pé e tornozelo",
             "Esportivo? Hálux valgo? Pé do diabético? Performance? Escolher UMA aresta torna você inesquecível em vez de mais um do guarda-chuva ICOD"),
            ("Construir marca pessoal paralela à ICOD",
             "Dr. Giancarlo Mariano e Dr. Joubert Toledo já têm clínica própria além do instituto — modelo paralelo, não conflitante. Hora de ter site, Instagram pessoal e jornada própria"),
            ("Subir ticket de R$350 para R$800-1.200",
             "Consulta avaliativa premium diferenciada da ICOD. Em Águas Claras, o paciente classe A paga sem hesitar quando entende o porquê"),
            ("Reduzir convênios de 54+ para 5-10 estratégicos",
             "Manter os de ticket mais alto, sair de Postal/Camed/Saúde Caixa. O paciente público funcionalismo é ICP errado para pé e tornozelo premium"),
        ],
        "pontos_internos": [
            "Sem Lattes, sem PubMed, sem palestras — operador 100% prático, não acadêmico",
            "Hierarquia interna ICOD: Giancarlo Mariano é RT (estrela técnica), Joubert Toledo é admin (clínica paralela em Lago Sul). Paulo Victor é o sócio operador — opera, não constrói marca individual",
            "Demografia pacientes: 40-70 anos · funcionários públicos federais e aposentados · classe média (não classe alta)",
            "1 review crítica (Esmeraldino, ago/24): 'faz cirurgia mas a mão de obra tem que pagar' = teto de monetização no modelo atual chocando com paciente",
            "Hipótese residência: HBDF ou HRAN (rotas clássicas DF) + fellowship HOG Goiânia ou IOT-HCFMUSP. CONFIRMAR na call",
            "Perfil presumido: introvertido técnico, alta empatia, baixa autopromoção. NÃO é alfa-influencer. Patrick deve perguntar mais que afirmar",
        ],
    },

    "tarik-soares-suleiman": {
        "quote_manifesto": "Você já vendeu liberdade pra 31 mil pessoas. Agora vamos vender pra você a sua própria.",
        "narrativa_publica": "Você se formou no ITPAC, fez residência em Cirurgia Geral no Maranhão, depois Cirurgia do Aparelho Digestivo na UFMA, e fechou com fellowship em videolaparoscopia avançada no Adventista Silvestre, Rio de Janeiro. Em 2019, aos 27 anos, foi co-autor do <em>primeiro transplante hepático intervivos para metástase colorretal da América Latina</em> — ao lado de Pál-Dag Line, da Universidade de Oslo, inventor mundial do protocolo. Voltou pra Araguaína e fez do Hospital São Lucas + ICOD a base. <em>Hoje, 31,6 mil pessoas seguem você no Instagram pra entender uma frase: 'liberdade de comer'.</em>",
        "descobertas_publicas": [
            "<strong>ITPAC Araguaína (graduação 2012)</strong> · Residência Cirurgia Geral SES-MA (2014) · Residência Cirurgia Aparelho Digestivo UFMA (2018) · Fellowship Videolaparoscopia Adventista Silvestre RJ (2019)",
            "<strong>Co-autor #8 de 11 do PRIMEIRO transplante hepático intervivos para metástase colorretal da América Latina</strong> (ABCD 2019, DOI 10.1590/0102-672020180001e1468)",
            "<strong>Co-autores</strong>: Eduardo de Souza M Fernandes (líder transplante hepático Brasil) · <strong>Pál-Dag Line</strong> (Oslo, inventor mundial do protocolo) · Orlando Jorge M Torres (UFMA)",
            "<strong>Paper técnico 2017</strong>: 'Modified Heidelberg Technique for Pancreatic Anastomosis' (ABCD)",
            "<strong>Sócio fundador ICOD Tocantins</strong> com Dr. Agamenon Dias de Oliveira Neto (cirurgião digestivo) — Instituto de Cirurgia de Obesidade e Diabetes",
            "<strong>Site próprio</strong> tariksuleiman.com.br/oficial · <strong>Instagram verificado azul</strong>: 31,6 mil seguidores · 816 posts",
            "<strong>Bio</strong>: 'Ajudo você a perder o medo e recuperar a liberdade de comer'",
            "<strong>Posicionamento cravado</strong>: Cirurgião de Vesícula (porta de entrada) · vesícula-hérnia-refluxo (3 funis técnicos) · bariátrica como transformação",
            "<strong>Hospital São Lucas Araguaína</strong> + ICOD (Avenida Tocantins 1640, Sala 106)",
        ],
        "pitch_direcionado": [
            ("Estruturar o 'Programa Liberdade de Comer' como produto",
             "Jornada de 6-12 meses: pré-cirúrgico + cirurgia + acompanhamento + comunidade · ticket único R$ 50-80k · sai de procedimento e vira transformação completa"),
            ("Posicionar Tarik Suleiman como marca-mãe e ICOD como infraestrutura",
             "Hoje a marca pessoal divide brilho com 3 sócios. Hora da marca individual virar protagonista, com ICOD como ativo institucional de apoio"),
            ("Construir mecanismo de turismo médico premium",
             "Captar paciente de Goiânia, Brasília, Belém, Manaus pra Araguaína. 31,6k seguidores não estão todos em Tocantins — é audiência nacional não monetizada"),
            ("Lançar mentoria/curso pra cirurgiões digestivos do Norte",
             "Replicar o método aprendido com Adventista Silvestre + UFMA. Construir o 'Club Norte' — comunidade de cirurgiões premium da região com você como hub"),
        ],
        "pontos_internos": [
            "Origem familiar libanesa-maranhense (DDD 98 + 5 anos no MA + sobrenome árabe). Existe Clínica Claudia Suleiman em Araguaína (parente — mãe? esposa?)",
            "MATEUS já segue o Tarik. Provável conexão UFMA — confirmar pré-call",
            "ICOD com 4 sócios + capital R$10k após 5 anos = teto operacional. Receita real fora do livro",
            "Sócio Jorge Luiz Carvalho Cunha Gomes Abrantes (entrou 2024) NÃO é médico — é dono de postos de gasolina. Sócio capitalista",
            "Vesícula domina conteúdo, mas BARIÁTRICA é o ticket alto. Misalignment de funil",
            "Frase ouro pro Patrick: 'Liberdade' é o nucleo dele — paralelo direto com VERSO/Essenza do Patrick",
            "Pitch hook: 'Você já vendeu liberdade pra 31 mil pessoas. Agora vamos vender pra você a sua própria — liberdade de não depender de volume, de sócio, de plantão'",
        ],
    },

    "julio-fran": {
        "quote_manifesto": "Você é o ortopedista mais difícil de pesquisar do grupo. Isso é decisão consciente?",
        "narrativa_publica": "Você atende em Timbó, no Vale do Itajaí, dentro da Clínica Ortopédica Serpa, ao lado do Dr. Ricardo Serpa e da equipe. Tem TEOT pela SBOT, subespecialização em quadril e joelho de adulto, e atende também o Hospital Oase. É o nome menos conhecido do grupo digitalmente — e é exatamente isso que mais nos chamou atenção. <em>Você pagou um sinal antes de ter qualquer garantia. Isso não é gesto de quem está confortável.</em>",
        "descobertas_publicas": [
            "<strong>CRM-SC 24030 · TEOT</strong> — Ortopedia e Traumatologia, subespecialização <strong>Quadril e Joelho de adulto (artroplastia)</strong>",
            "<strong>Médico associado da Clínica Ortopédica Serpa</strong>, comandada pelo Dr. Ricardo Serpa (CRM-SC 13813)",
            "<strong>Endereço da Clínica Serpa</strong>: Rua Bolívia 148, Sala 206 · Bairro Imigrantes · Timbó-SC",
            "<strong>Atende Hospital e Maternidade Oase (Timbó)</strong> + CENSIT (Centro de Saúde Timbó, mesmo prédio)",
            "<strong>Equipe Serpa</strong>: Ricardo Serpa, Guilherme Q. Rodrigues, Felipe Guadagnin, Alberto K. Miyamoto, Murillo Boldrini",
            "<strong>Aceita Unimed</strong> (cadastro AgendaConvenio)",
            "<strong>Vale do Itajaí</strong> — alta renda regional (Hering, Wegg, Cifial), Unimed forte, poucos especialistas em quadril/joelho jovens",
        ],
        "pitch_direcionado": [
            ("Sair da invisibilidade digital com ângulo correto",
             "Você é especialista em <strong>quadril e joelho de adulto</strong> (não pediátrico, como portais erram). Bio precisa cravar isso. 30 posts em 30 dias com casos cirúrgicos, técnica, recuperação"),
            ("Construir marca pessoal paralela à Clínica Serpa",
             "O Ricardo é referência local consolidada — você precisa do seu próprio espaço sem conflito. Site + Instagram pessoal + Doctoralia individual"),
            ("Eleger nicho dentro de quadril e joelho",
             "Artroplastia em paciente jovem (50-65 anos)? Lesões esportivas em adulto ativo? Revisão de prótese? Escolher UM ângulo + parcerias com clubes esportivos e academias do Vale"),
            ("Plano de saída gradual da Unimed",
             "Reduzir 30% de volume convênio em 90 dias. Capturar paciente premium de Joinville, Florianópolis e Blumenau via telemedicina + segunda opinião"),
        ],
        "pontos_internos": [
            "NÃO tem clínica própria — é associado da Serpa. Endereço Bolívia 148 NÃO é dele",
            "ATENÇÃO: subespecialidade real é QUADRIL E JOELHO ADULTO (artroplastia), não pediátrica como portais Unimed erram",
            "Hospital Oase encerrou ortopedia em 2025 = ele perdeu fonte de plantão/cirurgia. Está em ponto de virada — ou consolida agora ou some",
            "Origem provável: nasceu SP (DDD 11) → graduação UFMA Maranhão (processos TJMA confirmam) → migração SC (~2014-2016, CRM-SC 24030)",
            "38 anos · email juliofran86@gmail.com (nascido ~1986/87)",
            "Forasteiro silencioso em Timbó (cidade luterana/católica alemã, conservadora). Casamento com catarinense é hipótese forte (não confirmada)",
            "Abertura recomendada: 'Júlio, em 4 horas de busca achei 3 frases sobre você. Achei o telefone da Clínica Serpa, o CRM 24030, e a lista do Oase. Só. Comparado com o Ricardo, você é invisível digitalmente. E mesmo assim você pagou R$1k pra estar aqui'",
            "Cuidado: pagar R$1k sendo Urubu = sinal forte de busca, mas verificar capacidade financeira pra ticket CPP",
        ],
    },

    "marina-marangon-melhado": {
        "quote_manifesto": "Você construiu autoridade de mídia tier-1 antes de construir audiência. Agora a casa precisa caber a visita.",
        "narrativa_publica": "Você nasceu em Cuiabá, formou-se na UNIC e fez residência em Ortopedia na Beneficência Portuguesa de Ribeirão Preto. Aprofundou-se em Nutrologia com Dr. Lair Ribeiro, Nutrição Esportiva com Rodolfo Peres, e Hormonologia com Dr. Ítalo Rachid — a santíssima trindade da medicina integrativa brasileira. Mudou pra São Paulo, montou consultório no Jardim Paulista. Em 9 meses, você assinou seis matérias tier-1 — Correio Braziliense, Estado de Minas, THMais. <em>E perdeu 30 kg transformando seu próprio estilo de vida.</em> Esse é o seu Por Quê.",
        "descobertas_publicas": [
            "<strong>CRM-SP 179.632 · CRM-MT 7.454 · RQE 121.033 · CNRM 386646</strong>",
            "<strong>Trajetória</strong>: UNIC Cuiabá (graduação) → BP Ribeirão Preto (residência) → AGHA Brasil Jardim Paulista (clínica)",
            "<strong>Pós-graduações declaradas</strong>: Nutrologia Uningá com <strong>Dr. Lair Ribeiro</strong> · Nutrição Esportiva Plenitude com <strong>Rodolfo Peres</strong> · Hormonologia para Longevidade com <strong>Dr. Ítalo Rachid</strong> · habilitação terapias EV/IM",
            "<strong>Mídia tier-1 confirmada (9 meses)</strong>: Correio Braziliense (3x: fascite, joanete, entorse) · Estado de Minas Em Foco (hérnia de disco) · THMais NovaBrasil (2x: sapatos, batata da perna)",
            "<strong>Endereços</strong>: Clínica AGHA · R. Bento de Andrade, 436 · Jardim Paulista <em>+</em> sala satélite Joaquim Floriano, 413 · 9º andar · Itaim Bibi",
            "<strong>Manifesto pessoal declarado no site</strong>: 'Perdi 30 kg transformando meu estilo de vida'",
            "<strong>Manifesto comercial</strong>: 'Viver com dor não precisa ser o seu normal'",
            "<strong>Doctoralia</strong>: tabela transparente — Consulta R$ 300 · Retorno R$ 100 · Infiltração R$ 500 · <strong>Programa Emagrecimento Definitivo R$ 800</strong>",
            "<strong>Particular puro</strong> — não aceita NENHUM convênio (raro em ortopedia)",
            "<strong>Instagram verificado azul</strong> @dramarinamelhado · 100 seguidores · 14 posts (perfil recém-aberto/migrado)",
        ],
        "pitch_direcionado": [
            ("Subir ticket imediatamente: R$300 → R$1.500 consulta",
             "Paciente que paga R$300 hoje paga R$1.500 amanhã pela CNN Brasil + Correio + Jardim Paulista. Underpricing brutal pra autoridade que já construiu"),
            ("Consertar o site e nomear o método",
             "Site tem '555-555-5555' e 'meuemail@email.com.br' (placeholders de template) — funil quebrado vazando autoridade. Nomear o protocolo: 'Método Marina' / 'Sistema Integrativo X' — passa de ortopedista integrativa pra <em>dona de método</em>"),
            ("Construir o 'Programa Voltar à Corrida sem Dor'",
             "Empacotar a prática integrativa em jornada de 6 meses por R$ 18-30k · transformação completa, não consulta avulsa. Você já SABE empacotar (Emagrecimento Definitivo R$800) — basta escalar"),
            ("Ativar audiência própria e categoria nacional",
             "@dramarinamelhado precisa de 4-5 posts/semana em torno de UMA tese central ('seu corpo é sistema, não peça'). Newsletter pegando os leitores qualificados da CNN/Correio. Lista de espera pública. Categoria, não competidora"),
        ],
        "pontos_internos": [
            "Selo Meta Verified provavelmente PAGO (R$50/mês) — não é o selo lendário antigo. Mas é selo legítimo, valida autoridade",
            "Trauma fundador: 'perdi 30 kg' é o NORTE EMOCIONAL não monetizado. Mateus precisa puxar isso como manifesto",
            "Mentores DECLARADOS no Doctoralia: Lair Ribeiro + Rodolfo Peres + Ítalo Rachid (santíssima trindade integrativa)",
            "DNA é integrativa-hormonal-regenerativa, NÃO funcional-feminina. Não confundir com Ana Hirsch",
            "CNN Brasil auto-declarada no site mas sem matéria nominal indexada — perguntar direto na call",
            "Ela já EMPACOTOU 'Emagrecimento Definitivo R$ 800' — tem sementes de método. Precisa só escalar",
            "Subprecificada + sub-distribuída + super-credenciada = ICP CPP purebred",
            "Risco: pode chegar com 'já sei tudo'. Patrick abre com case de Águia que aplicou CPP, NÃO com conteúdo introdutório",
            "Possível parente: Laura Moraes Marangon Melhado, Silvio Sanches Melhado (registros) — investigar discreto",
            "Pitch mínimo: R$ 38-42k. Score 84",
        ],
    },

    "eduardo-watanabe-castanheira": {
        "quote_manifesto": "Você não precisa de mais paciente. Precisa de próximo patamar.",
        "narrativa_publica": "Você se formou na FCMMG entre 1989 e 1994, fez residência no Hospital Ortopédico de Belo Horizonte, e em 1998 fez fellowship em Cirurgia da Mão sob orientação direta do <strong>Dr. Arlindo Pardini Júnior</strong> — autor de 'Traumatismos da Mão', preceptor histórico, hoje aos 91 anos. Você nasceu em Belo Horizonte, foi pra Patos de Minas, e em 2017 a cidade te deu o título de <em>Cidadão Patense Honorífico</em> em sessão solene da Câmara. Em 2021, virou Diretor-Presidente da Unimed Patos de Minas. Em 2018, abriu CNPJ Ltda — estrutura societária que comporta sócio futuro. Trinta anos de carreira, dois RQEs, três sociedades titulares. <em>A pergunta é: quem você está formando?</em>",
        "descobertas_publicas": [
            "<strong>FCMMG Medicina (1989-1994)</strong> · Residência Ortopedia Hospital Ortopédico BH (1995-1997) · <strong>Fellowship Cirurgia da Mão sob Dr. Arlindo Pardini (1998)</strong>",
            "<strong>CRM-MG 27899 · RQE 12516 (Ortopedia) · RQE 12515 (Cirurgia da Mão)</strong>",
            "<strong>Cidadão Patense Honorífico</strong> — diploma entregue 25/05/2017 em Sessão Solene da Câmara Municipal (Vereador Braz Paulo de Oliveira Júnior)",
            "<strong>Diretor-Presidente da Unimed Patos de Minas</strong> (confirmado contexto agosto/2021)",
            "<strong>Membro Titular SBOT · SBCM (Cirurgia da Mão) · SBMH (Medicina Hiperbárica)</strong> — tríade rara",
            "<strong>Discípulo direto da escola Pardini</strong> — autor do livro-base brasileiro 'Traumatismos da Mão' (1985, 4ª edição), Presidente da IFSSH 2001-2006, treinou em Saigon na Guerra do Vietnã (1973, USAID)",
            "<strong>Pardini está vivo, 91 anos</strong>, casado com Jeanne Marie Jardim desde 1961",
            "<strong>3 frentes de atendimento</strong>: Consultório próprio R. Padre Caldeira 386 · HNSF (privado mais nobre de Patos) · Hospital Regional Antônio Dias",
            "<strong>CNPJ Eduardo Watanabe Castanheira Ltda</strong> — aberto 30/05/2018 · capital R$ 95.400 · Av. Getúlio Vargas 477 Apto 301 · Centro Patos de Minas",
        ],
        "pitch_direcionado": [
            ("Recuperar a história — Pardini, Patos, 30 anos",
             "Bio precisa cravar: '30 anos · 5.000+ mãos operadas · único cirurgião de mão formado pelo Pardini no Triângulo Mineiro'. Conteúdo de legado — histórias de pacientes operados há 20+ anos, evolução da cirurgia da mão, casos marcantes"),
            ("Construir telemedicina e segunda opinião pra cirurgia da mão",
             "Atender ortopedistas do interior MG/GO/TO via segunda opinião. Ticket R$ 800-1.500 por consulta. Replicar o método Pardini sem deixar o consultório"),
            ("Lançar programa de mentoria pra ortopedistas júnior",
             "Replicar a escola Pardini. R$ 30-60k por mentorado/ano. Construir 'Watanabe Cirurgia da Mão' como marca institucional que sobrevive à carreira individual"),
            ("Estruturar sucessão clínica e venda parcial",
             "Sócio júnior, filho seguindo medicina, ou venda parcial planejada. CNPJ Ltda já comporta. A pergunta agora é quem assume"),
        ],
        "pontos_internos": [
            "Nascido em BH, foi pra Patos depois — adotado, não nativo. Ponto-mestre de identidade",
            "Pardini está VIVO (91 anos) — usar presente: 'ele está vivo, ele te viu chegar onde chegou'",
            "Daniel Watanabe Ortopedista (@dr.danielwatanabe_ortopedista) NÃO é filho — é outro Watanabe (SP, FM ABC)",
            "Pergunta-mestre: 'Eduardo, você tem filhos seguindo medicina?'",
            "MBA FGV (Gestão Empresarial + Gestão Saúde) — não confirmado em fonte aberta. NÃO fingir saber. Perguntar 'em que ano?'",
            "Ascendência nipo-brasileira (nissei/sansei). Cultura japonesa = trabalho, disciplina, longevidade, vergonha de não deixar legado",
            "672 posts × 6.808 seguidores = 10 seg/post. ROI de conteúdo ridículo pra alguém com 30 anos",
            "Ltda 2018 (não Eireli) = comporta sócio futuro. Pergunta: 'abriu Ltda em 2018 pra incluir alguém?'",
            "Pitch direcionado: LEGADO INSTITUCIONAL. Premium não vende mais consulta — vende continuidade",
            "Score 82 · Águia estrutural · Urubu digital",
        ],
    },

    "felipe-ojeda": {
        "quote_manifesto": "Selo azul com mil seguidores não é falha. É antecipação. A Meta enxergou autoridade antes do mercado.",
        "narrativa_publica": "Você se formou em Medicina pela UFF em 2017, fez residência de Cirurgia Geral na FMABC (com TCBC + RQE 114019), o programa Harvard PPCR em pesquisa clínica, e está concluindo agora o Fellowship em Urologia Minimamente Invasiva pelo IDOR-SP — Rede D'Or — com Dr. Marco Antonio Quesada Fortes, Dr. Rodrigo Frota e Dr. Bruno Marroig. Ganhou um segundo RQE (146538) ao lado do primeiro. <em>Dois RQEs antes dos 30 anos é raro.</em> Tem site próprio, perfil verificado azul, posicionamento declarado em Tech, Performance e Saúde do Homem. <em>A engrenagem está montada certa. Falta combustível.</em>",
        "descobertas_publicas": [
            "<strong>UFF Niterói/RJ Medicina (2011-2017)</strong> · Residência Cirurgia Geral FMABC (2019-2021, TCBC, RQE 114019) · Harvard PPCR (2021) · <strong>Fellowship Urologia IDOR-SP em conclusão</strong> (2023-2026, RQE 146538)",
            "<strong>CRM-SP 202.291</strong>",
            "<strong>Dois RQEs</strong>: 114019 (Cirurgia Geral FMABC/TCBC) + 146538 (Urologia IDOR-SP) — autoridade técnica dupla rara",
            "<strong>Mentores IDOR-SP</strong>: Dr. Marco Antonio Quesada Fortes (coordenação geral) · Dr. Rodrigo Frota (cirurgia robótica) · Dr. Bruno Leonardo Marroig (endourologia)",
            "<strong>Programa inclui observership 1 mês na USC</strong> (University of Southern California) + Certificação Intuitive (da Vinci)",
            "<strong>Site próprio felipebulhoes.com</strong> + Newsletter mensal + Sintomas-checker interativo + 12 posts no blog",
            "<strong>Instagram verificado azul</strong> @drfelipebulhoes · 1.017 seguidores · 142 posts · Threads ativa",
            "<strong>Bio Instagram</strong>: 'Urologia IDOR-SP RQE 146538 | Cirurgia FMABC/TCBC RQE 114019 | Médico UFF CRM 202291 | Tech, Performance, Saúde do Homem'",
            "<strong>Doctoralia</strong>: 5,0/5,0 · 9 reviews · 1.500+ pacientes",
            "<strong>Posts Threads recentes (mar/2026)</strong>: simulador de robô, cálculo minimamente invasivo, andrologia, prótese peniana, cirurgia estética genital",
        ],
        "pitch_direcionado": [
            ("Cravar a aresta única dentro de Saúde do Homem",
             "Tech, Performance, Saúde do Homem promete três avenidas. O conteúdo público entrega 90% Srougi-clássico (próstata, cálculo). A aresta latente nos posts mais recentes (Threads): <strong>estética genital masculina premium + prótese peniana</strong> — vertical lucrativa, pouco ocupada em SP, ticket alto, paciente premium"),
            ("Construir o 'Programa Performance Masculina 360'",
             "Jornada de 6 meses com avaliação 360 + protocolo + acompanhamento + comunidade · ticket R$ 35-55k. Bioimpedância + TRH + check-up integrado masculino — você JÁ oferece no consultório, falta postar"),
            ("Conquistar 1 post/dia em torno da aresta escolhida",
             "Densidade vence frequência baixa. Threads ativa + Instagram verificado precisa traduzir autoridade institucional em tração de audiência"),
            ("Estruturar parcerias e canais que casam com o nicho",
             "Boxes de crossfit premium, clubes (Pinheiros/Hebraica), podcasts de performance/wellness. IDOR-SP como ativo institucional, marca pessoal Felipe Bulhões como ativo individual — coexistência estratégica"),
        ],
        "pontos_internos": [
            "Fellowship CONCLUINDO AGORA (mai/2026). Marco temporal forte pra pitch — 'que projeto sai junto?'",
            "Aresta REAL latente: prótese peniana + estética genital masculina (posts Threads mar/2026)",
            "Site oferece bioimpedância + TRH no consultório, mas blog não fala. Possível medo regulatório CFM sobre testosterona",
            "Vínculos Clinovi (4 unidades SP — Paulista, Moema, Pinheiros, SBC) + Campinas Day Hospital + CEMED Rede D'Or",
            "Origem RJ (UFF Niterói) → migrou pra SP (FMABC + IDOR). Movimento clássico do médico ambicioso",
            "Selo azul aos 1k seguidores = ele aplicou ativamente. Investimento pessoal alto em personal brand",
            "Dossiê inicial subestimou — NÃO é Pato cansado. É Águia em construção deliberada",
            "Score 75 · Águia em construção",
            "Pitch deve ser de aceleração, não de fundação. Tom: pares acelerando",
        ],
    },
}
